(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_transformer : ai_transform_create_options_t:Ai_transform_create_options.t -> Ai_transform_dto.t Lwt.t
val create_transformer_mappings : create_ai_transformer_mapping_options_t:Create_ai_transformer_mapping_options.t -> Ai_transform_mapping_dto.t Lwt.t
val delete_all_transformer_mappings : unit -> unit Lwt.t
val delete_transformer : id:string -> unit Lwt.t
val delete_transformer_mapping : id:string -> unit Lwt.t
val delete_transformers : unit -> unit Lwt.t
val export_transformer_results : export_transformer_options_t:Export_transformer_options.t -> Export_transformer_response.t Lwt.t
val generate_structured_content_from_attachment : generate_structured_content_attachment_options_t:Generate_structured_content_attachment_options.t -> Structured_content_result_dto.t Lwt.t
val generate_structured_content_from_email : generate_structured_content_email_options_t:Generate_structured_content_email_options.t -> Structured_content_result_dto.t Lwt.t
val generate_structured_content_from_sms : generate_structured_content_sms_options_t:Generate_structured_content_sms_options.t -> Structured_content_result_dto.t Lwt.t
val get_export_transformer_results_job : id:string -> Export_transformer_result_job_dto.t Lwt.t
val get_transformer : id:string -> Ai_transform_dto.t Lwt.t
val get_transformer_mapping : id:string -> Ai_transform_mapping_dto.t Lwt.t
val get_transformer_mappings : ?ai_transform_id:string -> ?entity_id:string -> ?entity_type:Enums.createaitransformermappingoptions_entitytype -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_ai_transform_mapping_projection.t Lwt.t
val get_transformer_result : id:string -> Ai_transform_result_dto.t Lwt.t
val get_transformer_results : ?email_id:string -> ?sms_id:string -> ?attachment_id:string -> ?ai_transform_id:string -> ?ai_transform_mapping_id:string -> ?entity_id:string -> ?entity_type:Enums.createaitransformermappingoptions_entitytype -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_ai_transform_result_projection.t Lwt.t
val get_transformer_results_table : include_meta_data:bool -> flatten_arrays_to_rows:bool -> ?email_id:string -> ?sms_id:string -> ?attachment_id:string -> ?ai_transform_id:string -> ?ai_transform_mapping_id:string -> ?entity_id:string -> ?entity_type:Enums.createaitransformermappingoptions_entitytype -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_table_data.t Lwt.t
val get_transformers : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?_include:string list -> unit -> Page_ai_transform_projection.t Lwt.t
val invoke_transformer : invoke_transformer_options_t:Invoke_transformer_options.t -> Conditional_structured_content_result.t Lwt.t
val test_transformer_mapping_match : id:string -> ?email_id:string -> ?sms_id:string -> ?attachment_id:string -> unit -> Ai_transform_mapping_match_result.t Lwt.t
val validate_structured_output_schema : structured_output_schema_t:Structured_output_schema.t -> Structured_output_schema_validation.t Lwt.t
