(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_transformer : options:Ai_tranform_create_options.t -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_ai_transform_projection.t Lwt.t
val create_transformer1 : ai_tranform_create_options_t:Ai_tranform_create_options.t -> Ai_transform_dto.t Lwt.t
val create_transformer_mappings : create_ai_transformer_mapping_options_t:Create_ai_transformer_mapping_options.t -> Ai_transform_mapping_dto.t Lwt.t
val delete_transformer : id:string -> unit Lwt.t
val delete_transformer_mapping : id:string -> unit Lwt.t
val delete_transformers : unit -> unit Lwt.t
val generate_structured_content_from_attachment : generate_structured_content_attachment_options_t:Generate_structured_content_attachment_options.t -> Structured_content_result_dto.t Lwt.t
val generate_structured_content_from_email : generate_structured_content_email_options_t:Generate_structured_content_email_options.t -> Structured_content_result_dto.t Lwt.t
val generate_structured_content_from_sms : generate_structured_content_sms_options_t:Generate_structured_content_sms_options.t -> Structured_content_result_dto.t Lwt.t
val get_transformer : id:string -> Ai_transform_dto.t Lwt.t
val get_transformer_mapping : id:string -> Ai_transform_mapping_dto.t Lwt.t
val get_transformer_mappings : ?ai_transform_id:string -> ?entity_id:string -> ?entity_type:Enums.createaitransformermappingoptions_entitytype -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_ai_transform_mapping_projection.t Lwt.t
val get_transformer_result : id:string -> Ai_transform_result_dto.t Lwt.t
val get_transformer_results : ?ai_transform_id:string -> ?ai_transform_mapping_id:string -> ?entity_id:string -> ?entity_type:Enums.createaitransformermappingoptions_entitytype -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_ai_transform_result_projection.t Lwt.t
val validate_structured_output_schema : structured_output_schema_t:Structured_output_schema.t -> Structured_output_schema_validation.t Lwt.t
