(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_audit_log_by_event_id : event_id:string -> ?since:string -> ?before:string -> unit -> Audit_log_event_dto.t Lwt.t
val get_audit_logs : ?since:string -> ?before:string -> ?action:string -> ?user_id:string -> ?actor_user_id:string -> ?target_user_id:string -> ?resource_type:string -> ?resource_id:string -> ?outcome:string -> ?request_id:string -> ?ip_address:string -> ?page_size:int32 -> ?cursor:string -> unit -> Audit_log_page_dto.t Lwt.t
val search_audit_logs : audit_log_search_options_t:Audit_log_search_options.t -> Audit_log_page_dto.t Lwt.t
