(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_json_property_as_string : property:string -> body:Yojson.Safe.t -> string Lwt.t
val get_user_info : unit -> User_info_dto.t Lwt.t
