(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_saml_user_or_create : key:string -> get_or_create_saml_user_options_t:Get_or_create_saml_user_options.t -> User_dto.t Lwt.t
