(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val upload_attachment : upload_options:Upload_attachment_options.t -> string list Lwt.t
val upload_attachment_bytes : ?string:string -> ?filename:string -> byte_array:string -> unit -> string list Lwt.t
val upload_multipart_form : file:string -> ?content_type:string -> ?filename:string -> ?x_filename:string -> unit -> string list Lwt.t
