(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val delete_all_attachments : unit -> unit Lwt.t
val delete_attachment : attachment_id:string -> unit Lwt.t
val download_attachment_as_base64_encoded : attachment_id:string -> Download_attachment_dto.t Lwt.t
val download_attachment_as_bytes : attachment_id:string -> string Lwt.t
val get_attachment : attachment_id:string -> Attachment_entity.t Lwt.t
val get_attachment_info : attachment_id:string -> Attachment_meta_data.t Lwt.t
val get_attachments : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?file_name_filter:string -> ?since:string -> ?before:string -> unit -> Page_attachment_entity.t Lwt.t
val upload_attachment : upload_attachment_options_t:Upload_attachment_options.t -> string list Lwt.t
val upload_attachment_bytes : request_body:string list -> ?content_type:string -> ?filename:string -> unit -> string list Lwt.t
val upload_multipart_form : ?content_type:string -> ?filename:string -> ?x_filename:string -> inline_object_t:Inline_object.t -> unit -> string list Lwt.t
