(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_bounced_email : id:string -> Bounced_email_dto.t Lwt.t
val get_bounced_emails : ?before:string -> ?page:int32 -> ?since:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_bounced_email.t Lwt.t
val get_bounced_recipient : id:string -> Bounced_recipient_dto.t Lwt.t
val get_bounced_recipients : ?before:string -> ?page:int32 -> ?since:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_bounced_recipients.t Lwt.t
