(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_new_email_address : ?allow_team_access:bool -> ?expires_at:string -> ?expires_in:int64 -> ?use_domain_pool:bool -> unit -> Inbox.t Lwt.t
val create_new_email_address1 : ?allow_team_access:bool -> ?expires_at:string -> ?expires_in:int64 -> ?use_domain_pool:bool -> unit -> Inbox.t Lwt.t
val empty_inbox : inbox_id:string -> unit Lwt.t
val send_email_simple : email_options:Simple_send_email_options.t -> unit Lwt.t
