(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_connector : create_connector_options_t:Create_connector_options.t -> Connector_dto.t Lwt.t
val delete_all_connector : unit -> unit Lwt.t
val delete_connector : id:string -> unit Lwt.t
val get_all_connector_sync_events : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> unit -> Page_connector_sync_events.t Lwt.t
val get_connector : id:string -> Connector_dto.t Lwt.t
val get_connector_sync_event : id:string -> Connector_sync_event_dto.t Lwt.t
val get_connector_sync_events : id:string -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> unit -> Page_connector_sync_events.t Lwt.t
val get_connectors : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> unit -> Page_connector.t Lwt.t
val sync_connector : id:string -> Connector_sync_request_result.t Lwt.t
val update_connector : id:string -> create_connector_options_t:Create_connector_options.t -> Connector_dto.t Lwt.t
