(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let cancel_device_preview_run ~run_id ~cancel_device_preview_run_options_t () =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}/cancel" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    let body = Request.write_as_json_body Cancel_device_preview_run_options.to_yojson cancel_device_preview_run_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Cancel_device_preview_run_result.of_yojson) resp body

let create_device_preview_feedback ~create_device_preview_feedback_options_t =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/feedback" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Create_device_preview_feedback_options.to_yojson create_device_preview_feedback_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_feedback_dto.of_yojson) resp body

let create_device_preview_run ~email_id ~create_device_preview_options_t () =
    let open Lwt in
    let uri = Request.build_uri "/emails/{emailId}/device-previews" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "emailId"  email_id in
    let body = Request.write_as_json_body Create_device_preview_options.to_yojson create_device_preview_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Create_device_preview_run_result.of_yojson) resp body

let delete_device_preview_run ~run_id =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Delete_device_preview_run_result.of_yojson) resp body

let ensure_device_preview_run ~email_id ~create_device_preview_options_t () =
    let open Lwt in
    let uri = Request.build_uri "/emails/{emailId}/device-previews/latest" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "emailId"  email_id in
    let body = Request.write_as_json_body Create_device_preview_options.to_yojson create_device_preview_options_t in
    Cohttp_lwt_unix.Client.call `PUT uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Create_device_preview_run_result.of_yojson) resp body

let get_device_preview_feedback ~feedback_id =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/feedback/{feedbackId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "feedbackId"  feedback_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_feedback_dto.of_yojson) resp body

let get_device_preview_feedback_items ?page ?size ?source ?run_id ?status ?provider ?category ?search () =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/feedback" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "page" Int32.to_string page in
    let uri = Request.maybe_add_query_param uri "size" Int32.to_string size in
    let uri = Request.maybe_add_query_param uri "source" Enums.show_source source in
    let uri = Request.maybe_add_query_param uri "runId"  run_id in
    let uri = Request.maybe_add_query_param uri "status" Enums.show_status status in
    let uri = Request.maybe_add_query_param uri "provider" Enums.show_providers provider in
    let uri = Request.maybe_add_query_param uri "category" Enums.show_category category in
    let uri = Request.maybe_add_query_param uri "search" (fun x -> x) search in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_feedback_list_dto.of_yojson) resp body

let get_device_preview_run ~run_id =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_run_dto.of_yojson) resp body

let get_device_preview_run_provider_progress ~run_id ~provider =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}/providers/{provider}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    let uri = Request.replace_path_param uri "provider" Enums.show_providers provider in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_provider_progress_dto.of_yojson) resp body

let get_device_preview_run_results ~run_id =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}/results" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_run_results_dto.of_yojson) resp body

let get_device_preview_run_screenshot ~run_id ~screenshot_id =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/{runId}/screenshots/{screenshotId}/image" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "runId"  run_id in
    let uri = Request.replace_path_param uri "screenshotId"  screenshot_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

let get_device_preview_runs ~email_id ?(limit = 50l) () =
    let open Lwt in
    let uri = Request.build_uri "/emails/{emailId}/device-previews" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "emailId"  email_id in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Device_preview_run_dto.of_yojson) resp body

let get_device_preview_runs_for_account ?(limit = 50l) () =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Device_preview_run_dto.of_yojson) resp body

let get_device_preview_runs_offset_paginated ~email_id ?(page = 0l) ?(size = 20l) ?(sort = `DESC) () =
    let open Lwt in
    let uri = Request.build_uri "/emails/{emailId}/device-previews/offset-paginated" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "emailId"  email_id in
    let uri = Request.add_query_param uri "page" Int32.to_string page in
    let uri = Request.add_query_param uri "size" Int32.to_string size in
    let uri = Request.add_query_param uri "sort" Enums.show_sortdirection sort in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Page_device_preview_run_projection.of_yojson) resp body

let update_device_preview_feedback ~feedback_id ~update_device_preview_feedback_options_t =
    let open Lwt in
    let uri = Request.build_uri "/emails/device-previews/feedback/{feedbackId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "feedbackId"  feedback_id in
    let body = Request.write_as_json_body Update_device_preview_feedback_options.to_yojson update_device_preview_feedback_options_t in
    Cohttp_lwt_unix.Client.call `PUT uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Device_preview_feedback_dto.of_yojson) resp body

