(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_domain_monitor : create_domain_monitor_options_t:Create_domain_monitor_options.t -> Domain_monitor_dto.t Lwt.t
val create_domain_monitor_alert_sink : monitor_id:string -> create_domain_monitor_alert_sink_options_t:Create_domain_monitor_alert_sink_options.t -> Domain_monitor_alert_sink_dto.t Lwt.t
val delete_domain_monitor : monitor_id:string -> unit Lwt.t
val delete_domain_monitor_alert_sink : monitor_id:string -> sink_id:string -> unit Lwt.t
val get_domain_monitor : monitor_id:string -> Domain_monitor_dto.t Lwt.t
val get_domain_monitor_alert_sinks : monitor_id:string -> Domain_monitor_alert_sink_dto.t list Lwt.t
val get_domain_monitor_insights : monitor_id:string -> ?since:string -> ?before:string -> unit -> Domain_monitor_insights_dto.t Lwt.t
val get_domain_monitor_runs : monitor_id:string -> ?since:string -> ?before:string -> ?status:Enums.laststatus -> ?limit:int32 -> unit -> Domain_monitor_run_dto.t list Lwt.t
val get_domain_monitor_series : monitor_id:string -> ?since:string -> ?before:string -> ?bucket:Enums.bucket -> unit -> Domain_monitor_series_dto.t Lwt.t
val get_domain_monitors : unit -> Domain_monitor_dto.t list Lwt.t
val run_domain_monitor_now : monitor_id:string -> Domain_monitor_run_now_result.t Lwt.t
val run_due_domain_monitors : ?max_runs:int32 -> unit -> Domain_monitor_run_due_result.t Lwt.t
val update_domain_monitor : monitor_id:string -> update_domain_monitor_options_t:Update_domain_monitor_options.t -> Domain_monitor_dto.t Lwt.t
