(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let add_domain_wildcard_catch_all ~id =
    let open Lwt in
    let uri = Request.build_uri "/domains/{id}/wildcard" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "id"  id in
    Cohttp_lwt_unix.Client.call `POST uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_dto.of_yojson) resp body

let create_domain ~create_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/domains" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Create_domain_options.to_yojson create_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_dto.of_yojson) resp body

let delete_domain ~id =
    let open Lwt in
    let uri = Request.build_uri "/domains/{id}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "id"  id in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.to_string) resp body

let get_available_domains ?inbox_type () =
    let open Lwt in
    let uri = Request.build_uri "/domains/available-domains" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "inboxType" Enums.show_inboxtype inbox_type in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_groups_dto.of_yojson) resp body

let get_domain ~id ?check_for_errors () =
    let open Lwt in
    let uri = Request.build_uri "/domains/{id}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "id"  id in
    let uri = Request.maybe_add_query_param uri "checkForErrors" string_of_bool check_for_errors in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_dto.of_yojson) resp body

let get_domain_issues () =
    let open Lwt in
    let uri = Request.build_uri "/domains/issues" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_issues_dto.of_yojson) resp body

let get_domain_wildcard_catch_all_inbox ~id =
    let open Lwt in
    let uri = Request.build_uri "/domains/{id}/wildcard" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "id"  id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Inbox_dto.of_yojson) resp body

let get_domains () =
    let open Lwt in
    let uri = Request.build_uri "/domains" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Domain_preview.of_yojson) resp body

let get_mail_slurp_domains ?inbox_type () =
    let open Lwt in
    let uri = Request.build_uri "/domains/mailslurp-domains" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "inboxType" Enums.show_inboxtype inbox_type in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_groups_dto.of_yojson) resp body

let update_domain ~id ~update_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/domains/{id}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "id"  id in
    let body = Request.write_as_json_body Update_domain_options.to_yojson update_domain_options_t in
    Cohttp_lwt_unix.Client.call `PUT uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Domain_dto.of_yojson) resp body

