(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let compare_email_audits ~audit_id ~other_audit_id =
    let open Lwt in
    let uri = Request.build_uri "/email-audits/{auditId}/compare/{otherAuditId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "auditId"  audit_id in
    let uri = Request.replace_path_param uri "otherAuditId"  other_audit_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Email_audit_comparison_dto.of_yojson) resp body

let create_email_audit ~create_email_audit_options_t =
    let open Lwt in
    let uri = Request.build_uri "/email-audits" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Create_email_audit_options.to_yojson create_email_audit_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Email_audit_dto.of_yojson) resp body

let delete_email_audit ~audit_id =
    let open Lwt in
    let uri = Request.build_uri "/email-audits/{auditId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "auditId"  audit_id in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let get_email_audit ~audit_id =
    let open Lwt in
    let uri = Request.build_uri "/email-audits/{auditId}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.replace_path_param uri "auditId"  audit_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Email_audit_dto.of_yojson) resp body

let get_email_audits ?email_id ?since ?before ?limit () =
    let open Lwt in
    let uri = Request.build_uri "/email-audits" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "emailId"  email_id in
    let uri = Request.maybe_add_query_param uri "since" (fun x -> x) since in
    let uri = Request.maybe_add_query_param uri "before" (fun x -> x) before in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Email_audit_dto.of_yojson) resp body

