(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_expiration_defaults : unit -> Expiration_defaults.t Lwt.t
val get_expired_inbox_by_inbox_id : inbox_id:string -> Expired_inbox_dto.t Lwt.t
val get_expired_inbox_record : expired_id:string -> Expired_inbox_dto.t Lwt.t
val get_expired_inboxes : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> unit -> Page_expired_inbox_record_projection.t Lwt.t
