(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_expiration_defaults : unit -> Expiration_defaults.t Lwt.t
val get_expired_inbox_by_inbox_id : inbox_id:string -> Expired_inbox_dto.t Lwt.t
val get_expired_inbox_record : id_of_the_expired_inbox_record_you_want_to_retrieve__this_is_different_from_the_id_of_the_inbox_you_are_interested_in__see_other_methods_for_getting_expired_inbox_record_for_an_inbox_inbox_id:string -> Expired_inbox_dto.t Lwt.t
val get_expired_inboxes : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> unit -> Page_expired_inbox_record_projection.t Lwt.t
