(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let submit_form ?_to ?_subject ?_email_address ?_success_message ?_spam_check ?other_parameters () =
    let open Lwt in
    let uri = Request.build_uri "/forms" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.init_form_encoded_body () in
    let body = Request.maybe_add_form_encoded_body_param body "_to" (fun x -> x) _to in
    let body = Request.maybe_add_form_encoded_body_param body "_subject" (fun x -> x) _subject in
    let body = Request.maybe_add_form_encoded_body_param body "_email_address" (fun x -> x) _email_address in
    let body = Request.maybe_add_form_encoded_body_param body "_success_message" (fun x -> x) _success_message in
    let body = Request.maybe_add_form_encoded_body_param body "_spam_check" (fun x -> x) _spam_check in
    let body = Request.maybe_add_form_encoded_body_param body "other_parameters" (fun x -> x) other_parameters in
    let body = Request.finalize_form_encoded_body body in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

