(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let submit_form ?_to ?_subject ?_redirect_to ?_email_address ?_success_message ?_spam_check ?other_parameters () =
    let open Lwt in
    let uri = Request.build_uri "/forms" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "_to" (fun x -> x) _to in
    let uri = Request.maybe_add_query_param uri "_subject" (fun x -> x) _subject in
    let uri = Request.maybe_add_query_param uri "_redirectTo" (fun x -> x) _redirect_to in
    let uri = Request.maybe_add_query_param uri "_emailAddress" (fun x -> x) _email_address in
    let uri = Request.maybe_add_query_param uri "_successMessage" (fun x -> x) _success_message in
    let uri = Request.maybe_add_query_param uri "_spamCheck" (fun x -> x) _spam_check in
    let uri = Request.maybe_add_query_param uri "otherParameters" (fun x -> x) other_parameters in
    Cohttp_lwt_unix.Client.call `POST uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

