(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_new_inbox_forwarder : create_inbox_forwarder_options:Create_inbox_forwarder_options.t -> ?inbox_id:string -> unit -> Inbox_forwarder_dto.t Lwt.t
val delete_inbox_forwarder : id:string -> unit Lwt.t
val delete_inbox_forwarders : ?inbox_id:string -> unit -> unit Lwt.t
val get_inbox_forwarder : id:string -> Inbox_forwarder_dto.t Lwt.t
val get_inbox_forwarders : ?inbox_id:string -> ?page:int32 -> ?search_filter:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_inbox_forwarder_dto.t Lwt.t
val test_inbox_forwarder : id:string -> inbox_forwarder_test_options:Inbox_forwarder_test_options.t -> Inbox_forwarder_test_result.t Lwt.t
val test_inbox_forwarders_for_inbox : inbox_id:string -> inbox_forwarder_test_options:Inbox_forwarder_test_options.t -> Inbox_forwarder_test_result.t Lwt.t
val test_new_inbox_forwarder : test_new_inbox_forwarder_options:Test_new_inbox_forwarder_options.t -> Inbox_forwarder_test_result.t Lwt.t
