(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_totp_device_for_custom : create_totp_device_otp_auth_url_options_t:Create_totp_device_otp_auth_url_options.t -> Totp_device_dto.t Lwt.t
val create_totp_device_for_otp_auth_url : create_totp_device_otp_auth_url_options_t:Create_totp_device_otp_auth_url_options.t -> Totp_device_dto.t Lwt.t
val get_totp_device : id:string -> Totp_device_dto.t Lwt.t
val get_totp_device_by : ?name:string -> ?issuer:string -> ?username:string -> unit -> Totp_device_optional_dto.t Lwt.t
val get_totp_device_code : id:string -> ?at:string -> ?min_seconds_until_expire:int32 -> unit -> Totp_device_code_dto.t Lwt.t
