(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_all_missed_emails : ?before:string -> ?inbox_id:string -> ?page:int32 -> ?search_filter:string -> ?since:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_missed_email_projection.t Lwt.t
val get_all_unknown_missed_emails : ?before:string -> ?inbox_id:string -> ?page:int32 -> ?search_filter:string -> ?since:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_unknown_missed_email_projection.t Lwt.t
val get_missed_email : missed_email_id:string -> Missed_email.t Lwt.t
val wait_for_nth_missed_email : ?before:string -> ?inbox_id:string -> ?index:int32 -> ?since:string -> ?timeout:int64 -> unit -> Missed_email.t Lwt.t
