(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_all_missed_emails : ?page:int32 -> ?search_filter:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_missed_email_projection.t Lwt.t
val get_missed_email : missed_email_id:string -> Missed_email.t Lwt.t
