(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_new_ruleset : create_ruleset_options_t:Create_ruleset_options.t -> ?inbox_id:string -> ?phone_id:string -> unit -> Ruleset_dto.t Lwt.t
val delete_ruleset : id:string -> unit Lwt.t
val delete_rulesets : ?inbox_id:string -> ?phone_id:string -> unit -> unit Lwt.t
val get_ruleset : id:string -> Ruleset_dto.t Lwt.t
val get_rulesets : ?inbox_id:string -> ?phone_id:string -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?search_filter:string -> ?since:string -> ?before:string -> unit -> Page_ruleset_dto.t Lwt.t
val test_inbox_rulesets_for_inbox : inbox_id:string -> ruleset_test_options_t:Ruleset_test_options.t -> Inbox_ruleset_test_result.t Lwt.t
val test_new_ruleset : test_new_inbox_ruleset_options_t:Test_new_inbox_ruleset_options.t -> Inbox_ruleset_test_result.t Lwt.t
val test_ruleset : id:string -> ruleset_test_options_t:Ruleset_test_options.t -> Inbox_ruleset_test_result.t Lwt.t
val test_ruleset_receiving : test_ruleset_receiving_options_t:Test_ruleset_receiving_options.t -> Test_ruleset_receiving_result.t Lwt.t
val test_ruleset_sending : test_inbox_ruleset_sending_options_t:Test_inbox_ruleset_sending_options.t -> Test_ruleset_sending_result.t Lwt.t
