(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_sent_email : id:string -> Sent_email_dto.t Lwt.t
val get_sent_emails : ?inbox_id:string -> ?page:int32 -> ?search_filter:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_sent_email_projection.t Lwt.t
val get_sent_organization_emails : ?inbox_id:string -> ?page:int32 -> ?search_filter:string -> ?size:int32 -> ?sort:Enums.sortdirection -> unit -> Page_sent_email_projection.t Lwt.t
