(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val delete_sms_message : sms_id:string -> unit Lwt.t
val delete_sms_messages : ?phone_number_id:string -> unit -> unit Lwt.t
val get_reply_for_sms_message : sms_id:string -> Reply_for_sms.t Lwt.t
val get_sms_count : unit -> Count_dto.t Lwt.t
val get_sms_message : sms_id:string -> Sms_dto.t Lwt.t
val get_sms_messages_paginated : ?phone_number:string -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?unread_only:bool -> ?since:string -> ?before:string -> unit -> Page_sms_projection.t Lwt.t
val get_unread_sms_count : unit -> Unread_count.t Lwt.t
val reply_to_sms_message : sms_id:string -> sms_reply_options_t:Sms_reply_options.t -> Sent_sms_dto.t Lwt.t
