(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val delete_sent_sms_message : sent_sms_id:string -> unit Lwt.t
val delete_sent_sms_messages : ?phone_number_id:string -> unit -> unit Lwt.t
val delete_sms_message : sms_id:string -> unit Lwt.t
val delete_sms_messages : ?phone_number_id:string -> unit -> unit Lwt.t
val get_all_sms_messages : ?phone_number:string -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> ?search:string -> ?favourite:bool -> ?_include:string list -> unit -> Page_sms_projection.t Lwt.t
val get_reply_for_sms_message : sms_id:string -> Reply_for_sms.t Lwt.t
val get_sent_sms_count : unit -> Count_dto.t Lwt.t
val get_sent_sms_message : sent_sms_id:string -> Sent_sms_dto.t Lwt.t
val get_sent_sms_messages_paginated : ?phone_number:string -> ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> ?search:string -> unit -> Page_sent_sms_projection.t Lwt.t
val get_sms_count : unit -> Count_dto.t Lwt.t
val get_sms_message : sms_id:string -> Sms_dto.t Lwt.t
val get_unread_sms_count : unit -> Unread_count.t Lwt.t
val reply_to_sms_message : sms_id:string -> sms_reply_options_t:Sms_reply_options.t -> Sent_sms_dto.t Lwt.t
val send_sms : sms_send_options_t:Sms_send_options.t -> ?from_phone_number:string -> ?from_phone_id:string -> unit -> Sent_sms_dto.t Lwt.t
val set_sms_favourited : sms_id:string -> favourited:bool -> Sms_dto.t Lwt.t
