(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let analyze_dmarc_report ~analyze_dmarc_report_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/analyze-dmarc-report" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Analyze_dmarc_report_options.to_yojson analyze_dmarc_report_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Analyze_dmarc_report_results.of_yojson) resp body

let analyze_email_headers ~analyze_email_headers_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/analyze-email-headers" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Analyze_email_headers_options.to_yojson analyze_email_headers_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Analyze_email_headers_results.of_yojson) resp body

let check_campaign_probe ~check_campaign_probe_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-campaign-probe" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_campaign_probe_options.to_yojson check_campaign_probe_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_campaign_probe_results.of_yojson) resp body

let check_dns_propagation ~check_dns_propagation_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-dns-propagation" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_dns_propagation_options.to_yojson check_dns_propagation_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_dns_propagation_results.of_yojson) resp body

let check_domain_monitor ~check_domain_monitor_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-domain-monitor" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_domain_monitor_options.to_yojson check_domain_monitor_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_domain_monitor_results.of_yojson) resp body

let check_email_audit ~check_email_audit_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-email-audit" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_email_audit_options.to_yojson check_email_audit_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Email_audit_analysis_result.of_yojson) resp body

let check_email_auth_stack ~check_email_auth_stack_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-email-auth-stack" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_email_auth_stack_options.to_yojson check_email_auth_stack_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_email_auth_stack_results.of_yojson) resp body

let check_email_blacklist ~check_email_blacklist_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-email-blacklists" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_email_blacklist_options.to_yojson check_email_blacklist_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_email_blacklist_results.of_yojson) resp body

let check_email_features_client_support ~check_email_features_client_support_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/check-email-features-client-support" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Check_email_features_client_support_options.to_yojson check_email_features_client_support_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_email_features_client_support_results.of_yojson) resp body

let create_new_fake_email_address () =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-email" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    Cohttp_lwt_unix.Client.call `POST uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap New_fake_email_address_result.of_yojson) resp body

let delete_new_fake_email_address ~email_address =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-email" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.add_query_param uri "emailAddress" (fun x -> x) email_address in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let generate_bimi_record ~generate_bimi_record_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/generate-bimi-record" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Generate_bimi_record_options.to_yojson generate_bimi_record_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Generate_bimi_record_results.of_yojson) resp body

let generate_dmarc_record ~generate_dmarc_record_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/generate-dmarc-record" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Generate_dmarc_record_options.to_yojson generate_dmarc_record_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Generate_dmarc_record_results.of_yojson) resp body

let generate_mta_sts_record ~generate_mta_sts_record_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/generate-mta-sts-record" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Generate_mta_sts_record_options.to_yojson generate_mta_sts_record_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Generate_mta_sts_record_results.of_yojson) resp body

let generate_spf_record ~generate_spf_record_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/generate-spf-record" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Generate_spf_record_options.to_yojson generate_spf_record_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Generate_spf_record_results.of_yojson) resp body

let generate_tls_reporting_record ~generate_tls_reporting_record_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/generate-tls-reporting-record" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Generate_tls_reporting_record_options.to_yojson generate_tls_reporting_record_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Generate_tls_reporting_record_results.of_yojson) resp body

let get_fake_email_by_email_address ~email_address =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-email/byEmailAddress" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.add_query_param uri "emailAddress" (fun x -> x) email_address in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Fake_email_result.of_yojson) resp body

let get_fake_email_by_id ~id =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-email" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.add_query_param uri "id"  id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Fake_email_result.of_yojson) resp body

let get_fake_email_raw ~id =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-email/html" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.add_query_param uri "id"  id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

let get_fake_emails_for_address ~email_address ?page () =
    let open Lwt in
    let uri = Request.build_uri "/tools/fake-emails" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let uri = Request.maybe_add_query_param uri "page" Int32.to_string page in
    let uri = Request.add_query_param uri "emailAddress" (fun x -> x) email_address in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Fake_email_preview.of_yojson) resp body

let lookup_bimi_domain ~lookup_bimi_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-bimi-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_bimi_domain_options.to_yojson lookup_bimi_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_bimi_domain_results.of_yojson) resp body

let lookup_dkim_domain ~lookup_dkim_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-dkim-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_dkim_domain_options.to_yojson lookup_dkim_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_dkim_domain_results.of_yojson) resp body

let lookup_dmarc_domain ~lookup_dmarc_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-dmarc-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_dmarc_domain_options.to_yojson lookup_dmarc_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_dmarc_domain_results.of_yojson) resp body

let lookup_mta_sts_domain ~lookup_mta_sts_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-mta-sts-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_mta_sts_domain_options.to_yojson lookup_mta_sts_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_mta_sts_domain_results.of_yojson) resp body

let lookup_mx_record ~lookup_mx_records_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-mx-records" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_mx_records_options.to_yojson lookup_mx_records_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_mx_records_results.of_yojson) resp body

let lookup_ptr ~lookup_ptr_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-ptr" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_ptr_options.to_yojson lookup_ptr_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_ptr_results.of_yojson) resp body

let lookup_spf_domain ~lookup_spf_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-spf-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_spf_domain_options.to_yojson lookup_spf_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_spf_domain_results.of_yojson) resp body

let lookup_tls_reporting_domain ~lookup_tls_reporting_domain_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/lookup-tls-reporting-domain" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Lookup_tls_reporting_domain_options.to_yojson lookup_tls_reporting_domain_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Lookup_tls_reporting_domain_results.of_yojson) resp body

let test_smtp_server ~test_smtp_server_options_t =
    let open Lwt in
    let uri = Request.build_uri "/tools/test-smtp-server" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "x-api-key" Request.api_key in
    let body = Request.write_as_json_body Test_smtp_server_options.to_yojson test_smtp_server_options_t in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Test_smtp_server_results.of_yojson) resp body

