(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_tracking_pixel : create_tracking_pixel_options_t:Create_tracking_pixel_options.t -> Tracking_pixel_dto.t Lwt.t
val get_all_tracking_pixels : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?search_filter:string -> ?since:string -> ?before:string -> unit -> Page_tracking_pixel_projection.t Lwt.t
val get_tracking_pixel : id:string -> Tracking_pixel_dto.t Lwt.t
