(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val create_or_update_inbox_retention_policy_for_account : create_inbox_retention_policy_for_account_options_t:Create_inbox_retention_policy_for_account_options.t -> Inbox_retention_policy_dto.t Lwt.t
val delete_inbox_retention_policy_for_account : unit -> Empty_response_dto.t Lwt.t
val get_entity_automations : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> ?inbox_id:string -> ?phone_id:string -> ?filter:Enums.automationtype -> unit -> Page_entity_automation_items.t Lwt.t
val get_entity_events : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> ?inbox_id:string -> ?email_id:string -> ?phone_id:string -> ?sms_id:string -> ?attachment_id:string -> ?filter:Enums.entityeventitemprojection_eventtype -> unit -> Page_entity_event_items.t Lwt.t
val get_entity_favorites : ?page:int32 -> ?size:int32 -> ?sort:Enums.sortdirection -> ?since:string -> ?before:string -> ?filter:Enums.entitytype -> unit -> Page_entity_favourite_items.t Lwt.t
val get_inbox_retention_policy_for_account : unit -> Inbox_retention_policy_optional_dto.t Lwt.t
val get_json_property_as_string : property:string -> body:Yojson.Safe.t -> string Lwt.t
val get_user_info : unit -> User_info_dto.t Lwt.t
