(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Abstract_webhook_payload.t : Abstract webhook payload. Use the correct payload type for your webhook event type in order to access all the specific properties for that event. See the `NEW_EMAIL`,`NEW_CONTACT`, `NEW_ATTACHMENT` and `EMAIL_OPENED` payloads for the properties available for those events.
 *)

type t = {
    event_name: Enums.eventname option [@default None];
    webhook_id: string option [@default None];
    message_id: string option [@default None];
    webhook_name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Abstract webhook payload. Use the correct payload type for your webhook event type in order to access all the specific properties for that event. See the `NEW_EMAIL`,`NEW_CONTACT`, `NEW_ATTACHMENT` and `EMAIL_OPENED` payloads for the properties available for those events. *)
let create () : t = {
    event_name = None;
    webhook_id = None;
    message_id = None;
    webhook_name = None;
}

