(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    conditions: string list;
    instructions: string list;
    output_schema: Structured_output_schema.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    conditions = [];
    instructions = [];
    output_schema = None;
}

