(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    conditions: string list;
    instructions: string list;
    output_schema: Structured_output_schema.t option [@default None];
    name: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) : t = {
    conditions = [];
    instructions = [];
    output_schema = None;
    name = None;
    id = id;
}

