(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    id: string;
    user_id: string;
    created_at: string;
    entity_type: Enums.createdeliverabilitytestoptions_scope;
    ai_transform_id: string;
    entity_id: string option [@default None];
    content_selector: Enums.contentselector option [@default None];
    trigger_selector: Enums.triggerselector option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (created_at : string) (entity_type : Enums.createdeliverabilitytestoptions_scope) (ai_transform_id : string) : t = {
    name = None;
    id = id;
    user_id = user_id;
    created_at = created_at;
    entity_type = entity_type;
    ai_transform_id = ai_transform_id;
    entity_id = None;
    content_selector = None;
    trigger_selector = None;
}

