(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    attachment_id: string;
    content_length: int64 option [@default None];
    content_type: string option [@default None];
    created_at: string;
    id: string option [@default None];
    name: string option [@default None];
    updated_at: string;
    user_id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (attachment_id : string) (created_at : string) (updated_at : string) (user_id : string) : t = {
    attachment_id = attachment_id;
    content_length = None;
    content_type = None;
    created_at = created_at;
    id = None;
    name = None;
    updated_at = updated_at;
    user_id = user_id;
}

