(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    tenant_id: string;
    dt: string option [@default None];
    event_id: string;
    event_ts: string;
    action: string;
    user_id: string option [@default None];
    actor_user_id: string option [@default None];
    target_user_id: string option [@default None];
    resource_type: string option [@default None];
    resource_id: string option [@default None];
    outcome: string option [@default None];
    request_id: string option [@default None];
    ip_address: string option [@default None];
    metadata_json: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (tenant_id : string) (event_id : string) (event_ts : string) (action : string) : t = {
    tenant_id = tenant_id;
    dt = None;
    event_id = event_id;
    event_ts = event_ts;
    action = action;
    user_id = None;
    actor_user_id = None;
    target_user_id = None;
    resource_type = None;
    resource_id = None;
    outcome = None;
    request_id = None;
    ip_address = None;
    metadata_json = None;
}

