(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    since: string option [@default None];
    before: string option [@default None];
    action: string option [@default None];
    user_id: string option [@default None];
    actor_user_id: string option [@default None];
    target_user_id: string option [@default None];
    resource_type: string option [@default None];
    resource_id: string option [@default None];
    outcome: string option [@default None];
    request_id: string option [@default None];
    ip_address: string option [@default None];
    event_id: string option [@default None];
    page_size: int32 option [@default None];
    cursor: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    since = None;
    before = None;
    action = None;
    user_id = None;
    actor_user_id = None;
    target_user_id = None;
    resource_type = None;
    resource_id = None;
    outcome = None;
    request_id = None;
    ip_address = None;
    event_id = None;
    page_size = None;
    cursor = None;
}

