(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    phone_number: string;
    phone_country: Enums.phonecountry;
    phone_variant: Enums.phonevariant option [@default None];
    line_type: string option [@default None];
    carrier_name: string option [@default None];
    mobile_country_code: string option [@default None];
    mobile_network_code: string option [@default None];
    provider_label: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (phone_number : string) (phone_country : Enums.phonecountry) : t = {
    phone_number = phone_number;
    phone_country = phone_country;
    phone_variant = None;
    line_type = None;
    carrier_name = None;
    mobile_country_code = None;
    mobile_network_code = None;
    provider_label = None;
}

