(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Basic_auth_options.t : Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints.
 *)

type t = {
    username: string option [@default None];
    password: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints. *)
let create () : t = {
    username = None;
    password = None;
}

