(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Basic_auth_options.t : Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints.
 *)

type t = {
    username: string;
    password: string;
} [@@deriving yojson { strict = false }, show ];;

(** Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints. *)
let create (username : string) (password : string) : t = {
    username = username;
    password = password;
}

