(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounce_recipient_projection.t : Bounced recipient
 *)

type t = {
    sent_email_id: string option [@default None];
    recipient: string;
    bounce_type: string option [@default None];
    action: string option [@default None];
    created_at: string;
    id: string option [@default None];
    status: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Bounced recipient *)
let create (recipient : string) (created_at : string) : t = {
    sent_email_id = None;
    recipient = recipient;
    bounce_type = None;
    action = None;
    created_at = created_at;
    id = None;
    status = None;
}

