(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounce_recipient.t : Bounced email recipient address
 *)

type t = {
    id: string;
    user_id: string option [@default None];
    recipient: string;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Bounced email recipient address *)
let create (id : string) (recipient : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    user_id = None;
    recipient = recipient;
    created_at = created_at;
    updated_at = updated_at;
}

