(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounced_email_dto.t : Bounced email
 *)

type t = {
    id: string;
    user_id: string;
    notification_type: string;
    sent_to_recipients: string list;
    sender: string;
    bounce_mta: string option [@default None];
    bounce_type: string option [@default None];
    bounce_recipients: string list;
    bounce_sub_type: string option [@default None];
    sent_email_id: string option [@default None];
    subject: string option [@default None];
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Bounced email *)
let create (id : string) (user_id : string) (notification_type : string) (sender : string) (created_at : string) : t = {
    id = id;
    user_id = user_id;
    notification_type = notification_type;
    sent_to_recipients = [];
    sender = sender;
    bounce_mta = None;
    bounce_type = None;
    bounce_recipients = [];
    bounce_sub_type = None;
    sent_email_id = None;
    subject = None;
    created_at = created_at;
}

