(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounced_recipient_dto.t : Bounced recipient
 *)

type t = {
    id: string option [@default None];
    user_id: string option [@default None];
    sent_email_id: string option [@default None];
    recipient: string;
    diagnostic_code: string option [@default None];
    action: string option [@default None];
    status: string option [@default None];
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Bounced recipient *)
let create (recipient : string) (created_at : string) : t = {
    id = None;
    user_id = None;
    sent_email_id = None;
    recipient = recipient;
    diagnostic_code = None;
    action = None;
    status = None;
    created_at = created_at;
}

