(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounced_recipient_dto.t : Bounced recipient
 *)

type t = {
    created_at: string;
    id: string option [@default None];
    recipient: string;
    user_id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Bounced recipient *)
let create (created_at : string) (recipient : string) (user_id : string) : t = {
    created_at = created_at;
    id = None;
    recipient = recipient;
    user_id = user_id;
}

