(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    bounce_mta: string option [@default None];
    bounce_recipients: string list;
    bounce_sub_type: string option [@default None];
    bounce_type: string option [@default None];
    created_at: string;
    id: string option [@default None];
    notification_type: string;
    sender: string;
    sent_to_recipients: string list;
    updated_at: string;
    user_id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (created_at : string) (notification_type : string) (sender : string) (updated_at : string) (user_id : string) : t = {
    bounce_mta = None;
    bounce_recipients = [];
    bounce_sub_type = None;
    bounce_type = None;
    created_at = created_at;
    id = None;
    notification_type = notification_type;
    sender = sender;
    sent_to_recipients = [];
    updated_at = updated_at;
    user_id = user_id;
}

