(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Bounce_projection.t : Bounced email event
 *)

type t = {
    id: string option [@default None];
    sender: string;
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Bounced email event *)
let create (sender : string) (created_at : string) : t = {
    id = None;
    sender = sender;
    created_at = created_at;
}

