(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    created_at: string;
    id: string option [@default None];
    sender: string;
} [@@deriving yojson { strict = false }, show ];;

let create (created_at : string) (sender : string) : t = {
    created_at = created_at;
    id = None;
    sender = sender;
}

