(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    probe_id: string;
    since: string;
    before: string;
    bucket: Enums.bucket;
    points: Campaign_probe_series_point_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (probe_id : string) (since : string) (before : string) (bucket : Enums.bucket) (points : Campaign_probe_series_point_dto.t list) : t = {
    probe_id = probe_id;
    since = since;
    before = before;
    bucket = bucket;
    points = points;
}

