(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Check_campaign_probe_options.t : One-shot public campaign probe preflight check options
 *)

type t = {
    (* Optional sender email address *)
    from_address: string option [@default None];
    (* Optional message subject *)
    subject: string option [@default None];
    (* Optional recipient email address for context *)
    recipient: string option [@default None];
    (* Optional caller supplied message id *)
    message_id: string option [@default None];
    (* HTML body content to analyze *)
    html_body: string option [@default None];
    (* Text body content to analyze when HTML is absent *)
    text_body: string option [@default None];
    (* Optional captcha token when captcha protection is enabled *)
    captcha_token: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** One-shot public campaign probe preflight check options *)
let create () : t = {
    from_address = None;
    subject = None;
    recipient = None;
    message_id = None;
    html_body = None;
    text_body = None;
    captcha_token = None;
}

