(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Check_email_client_support_options.t : Options for the email to be validated
 *)

type t = {
    email_body: string;
} [@@deriving yojson { strict = false }, show ];;

(** Options for the email to be validated *)
let create (email_body : string) : t = {
    email_body = email_body;
}

