(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Code_candidate.t : Candidate verification code extracted from content
 *)

type t = {
    (* Extracted code value *)
    code: string;
    (* Relative confidence score from 0 to 1 *)
    confidence: float;
    (* Extraction strategy for verification codes. Unsupported strategies may fall back when allowFallback is true. *)
    _method: Enums.extractcodesoptions_method;
    (* Source fragment used for extraction, for example RAW_TEXT_PART or SMS_BODY *)
    source: string;
    (* Nearby text context useful for debugging extraction decisions *)
    context: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Candidate verification code extracted from content *)
let create (code : string) (confidence : float) (_method : Enums.extractcodesoptions_method) (source : string) : t = {
    code = code;
    confidence = confidence;
    _method = _method;
    source = source;
    context = None;
}

