(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Condition_option.t : Options for matching emails in an inbox based on a condition such as `HAS_ATTACHMENTS=TRUE`
 *)

type t = {
    (* The condition to evaluate against the email *)
    condition: Enums.condition option [@default Some(`HAS_ATTACHMENTS)];
    (* What the condition should evaluate to. A string 'TRUE|FALSE' not a boolean. *)
    value: Enums.value option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for matching emails in an inbox based on a condition such as `HAS_ATTACHMENTS=TRUE` *)
let create () : t = {
    condition = None;
    value = None;
}

