(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    connector_id: string;
    status: Enums.connectoreventprojection_status;
    event_type: Enums.connectoreventprojection_eventtype;
    size: int64;
    message: string option [@default None];
    logs: string option [@default None];
    seen: bool option [@default None];
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (connector_id : string) (status : Enums.connectoreventprojection_status) (event_type : Enums.connectoreventprojection_eventtype) (size : int64) (created_at : string) : t = {
    id = id;
    connector_id = connector_id;
    status = status;
    event_type = event_type;
    size = size;
    message = None;
    logs = None;
    seen = None;
    created_at = created_at;
}

