(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Connector_sync_event_projection.t : ConnectorSyncEventProjection
 *)

type t = {
    message: string option [@default None];
    id: string option [@default None];
    created_at: string;
    connector_id: string;
    sync_count: int64;
    sync_status: Enums.syncstatus;
} [@@deriving yojson { strict = false }, show ];;

(** ConnectorSyncEventProjection *)
let create (created_at : string) (connector_id : string) (sync_count : int64) (sync_status : Enums.syncstatus) : t = {
    message = None;
    id = None;
    created_at = created_at;
    connector_id = connector_id;
    sync_count = sync_count;
    sync_status = sync_status;
}

