(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    connector_id: string;
    imap_host: string;
    imap_port: int32 option [@default None];
    imap_username: string option [@default None];
    imap_password: string option [@default None];
    imap_ssl: bool option [@default None];
    select_folder: string option [@default None];
    search_terms: string option [@default None];
    start_tls: bool option [@default None];
    proxy_host: string option [@default None];
    proxy_port: int32 option [@default None];
    proxy_enabled: bool option [@default None];
    local_host_name: string option [@default None];
    mechanisms: string list;
    ssl_protocols: string list;
    ssl_trust: string option [@default None];
    enabled: bool option [@default None];
    created_at: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (connector_id : string) (imap_host : string) (created_at : string) (id : string) : t = {
    connector_id = connector_id;
    imap_host = imap_host;
    imap_port = None;
    imap_username = None;
    imap_password = None;
    imap_ssl = None;
    select_folder = None;
    search_terms = None;
    start_tls = None;
    proxy_host = None;
    proxy_port = None;
    proxy_enabled = None;
    local_host_name = None;
    mechanisms = [];
    ssl_protocols = [];
    ssl_trust = None;
    enabled = None;
    created_at = created_at;
    id = id;
}

