(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Connector_projection.t : Connector
 *)

type t = {
    created_at: string;
    inbox_id: string;
    user_id: string;
    sync_enabled: bool;
    connector_type: Enums.connectortype[@default `IMAP];
    sync_schedule_type: Enums.syncscheduletype[@default `INTERVAL];
    sync_interval: int32 option [@default None];
    id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Connector *)
let create (created_at : string) (inbox_id : string) (user_id : string) (sync_enabled : bool) (connector_type : Enums.connectortype) (sync_schedule_type : Enums.syncscheduletype) : t = {
    created_at = created_at;
    inbox_id = inbox_id;
    user_id = user_id;
    sync_enabled = sync_enabled;
    connector_type = connector_type;
    sync_schedule_type = sync_schedule_type;
    sync_interval = None;
    id = None;
}

