(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    connector_id: string;
    sync_status: Enums.syncstatus;
    sync_count: int64;
    message: string option [@default None];
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (connector_id : string) (sync_status : Enums.syncstatus) (sync_count : int64) (created_at : string) : t = {
    id = id;
    connector_id = connector_id;
    sync_status = sync_status;
    sync_count = sync_count;
    message = None;
    created_at = created_at;
}

