(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    connector_id: string;
    smtp_host: string;
    smtp_port: int32 option [@default None];
    smtp_username: string option [@default None];
    smtp_password: string option [@default None];
    smtp_ssl: bool option [@default None];
    start_tls: bool option [@default None];
    smtp_mechanisms: string list;
    local_host_name: string option [@default None];
    proxy_host: string option [@default None];
    proxy_port: int32 option [@default None];
    proxy_enabled: bool option [@default None];
    enabled: bool option [@default None];
    ssl_trust: string option [@default None];
    ssl_protocols: string list;
    created_at: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (connector_id : string) (smtp_host : string) (created_at : string) (id : string) : t = {
    connector_id = connector_id;
    smtp_host = smtp_host;
    smtp_port = None;
    smtp_username = None;
    smtp_password = None;
    smtp_ssl = None;
    start_tls = None;
    smtp_mechanisms = [];
    local_host_name = None;
    proxy_host = None;
    proxy_port = None;
    proxy_enabled = None;
    enabled = None;
    ssl_trust = None;
    ssl_protocols = [];
    created_at = created_at;
    id = id;
}

