(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    user_id: string;
    connector_id: string;
    sync_enabled: bool;
    sync_schedule_type: Enums.syncscheduletype option [@default Some(`INTERVAL)];
    sync_interval: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (connector_id : string) (sync_enabled : bool) : t = {
    id = id;
    user_id = user_id;
    connector_id = connector_id;
    sync_enabled = sync_enabled;
    sync_schedule_type = None;
    sync_interval = None;
}

