(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Connector_event_projection.t : ConnectorEventProjection
 *)

type t = {
    event_type: Enums.connectoreventprojection_eventtype;
    created_at: string;
    connector_id: string;
    seen: bool option [@default None];
    message: string option [@default None];
    id: string option [@default None];
    size: int64;
    status: Enums.connectoreventprojection_status;
} [@@deriving yojson { strict = false }, show ];;

(** ConnectorEventProjection *)
let create (event_type : Enums.connectoreventprojection_eventtype) (created_at : string) (connector_id : string) (size : int64) (status : Enums.connectoreventprojection_status) : t = {
    event_type = event_type;
    created_at = created_at;
    connector_id = connector_id;
    seen = None;
    message = None;
    id = None;
    size = size;
    status = status;
}

