(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    enabled: bool;
    user_id: string;
    connector_type: Enums.connectortype[@default `IMAP];
    connector_auth_type: Enums.connectorauthtype[@default `PLAIN_TEXT];
    sync_enabled: bool;
    sync_schedule_type: Enums.syncscheduletype[@default `INTERVAL];
    sync_interval: int32 option [@default None];
    imap_host: string option [@default None];
    imap_port: int32 option [@default None];
    imap_username: string option [@default None];
    imap_password: string option [@default None];
    imap_ssl: bool option [@default None];
    select_folder: string option [@default None];
    search_terms: string option [@default None];
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (enabled : bool) (user_id : string) (connector_type : Enums.connectortype) (connector_auth_type : Enums.connectorauthtype) (sync_enabled : bool) (sync_schedule_type : Enums.syncscheduletype) (created_at : string) : t = {
    id = id;
    enabled = enabled;
    user_id = user_id;
    connector_type = connector_type;
    connector_auth_type = connector_auth_type;
    sync_enabled = sync_enabled;
    sync_schedule_type = sync_schedule_type;
    sync_interval = None;
    imap_host = None;
    imap_port = None;
    imap_username = None;
    imap_password = None;
    imap_ssl = None;
    select_folder = None;
    search_terms = None;
    created_at = created_at;
}

