(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Connector_projection.t : Connector
 *)

type t = {
    enabled: bool option [@default None];
    inbox_id: string;
    user_id: string;
    email_address: string option [@default None];
    created_at: string;
    name: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Connector *)
let create (inbox_id : string) (user_id : string) (created_at : string) (id : string) : t = {
    enabled = None;
    inbox_id = inbox_id;
    user_id = user_id;
    email_address = None;
    created_at = created_at;
    name = None;
    id = id;
}

