(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    connector_id: string;
    smtp_host: string option [@default None];
    smtp_port: int32 option [@default None];
    smtp_username: string option [@default None];
    smtp_password: string option [@default None];
    smtp_ssl: bool option [@default None];
    enabled: bool option [@default None];
    created_at: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (connector_id : string) (created_at : string) (id : string) : t = {
    connector_id = connector_id;
    smtp_host = None;
    smtp_port = None;
    smtp_username = None;
    smtp_password = None;
    smtp_ssl = None;
    enabled = None;
    created_at = created_at;
    id = id;
}

