(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Contact_projection.t : Email contact for address book
 *)

type t = {
    id: string;
    group_id: string option [@default None];
    created_at: string;
    first_name: string option [@default None];
    last_name: string option [@default None];
    company: string option [@default None];
    email_addresses: string list;
    opt_out: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Email contact for address book *)
let create (id : string) (created_at : string) : t = {
    id = id;
    group_id = None;
    created_at = created_at;
    first_name = None;
    last_name = None;
    company = None;
    email_addresses = [];
    opt_out = None;
}

