(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Content_match_options.t : Options for matching content using regex patterns based on Java Pattern syntax
 *)

type t = {
    (* Java style regex pattern. Do not include the typical `/` at start or end of regex in some languages. Given an example `your code is: 12345` the pattern to extract match looks like `code is: (\\d{6})`. This will return an array of matches with the first matching the entire pattern and the subsequent matching the groups: `['code is: 123456', '123456']` See https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html for more information of available patterns. *)
    pattern: string;
} [@@deriving yojson { strict = false }, show ];;

(** Options for matching content using regex patterns based on Java Pattern syntax *)
let create (pattern : string) : t = {
    pattern = pattern;
}

