(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string option [@default None];
    group_id: string option [@default None];
    first_name: string option [@default None];
    last_name: string option [@default None];
    company: string option [@default None];
    email_addresses: string list;
    opt_out: bool option [@default None];
    created_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    group_id = None;
    first_name = None;
    last_name = None;
    company = None;
    email_addresses = [];
    opt_out = None;
    created_at = None;
}

