(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Count_dto.t : Number of elements
 *)

type t = {
    total_elements: int64;
} [@@deriving yojson { strict = false }, show ];;

(** Number of elements *)
let create (total_elements : int64) : t = {
    total_elements = total_elements;
}

