(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_inbox_forwarder_options.t : Options for creating an inbox forwarder
 *)

type t = {
    (* Field to match against to trigger inbox forwarding for inbound email *)
    field: Enums.inboxautomationmatchoption_field option [@default None];
    (* String or wildcard style match for field specified when evaluating forwarding rules *)
    _match: string option [@default None];
    (* Email addresses to forward an email to if it matches the field and match criteria of the forwarder *)
    forward_to_recipients: string list;
    (* Comparison mode for inbox automation matching. *)
    should: Enums.inboxautomationmatchoption_should option [@default None];
    match_options: Inbox_automation_match_options.t option [@default None];
    (* Method for extracting text from attachments. *)
    attachment_text_extraction_method: Enums.attachmenttextextractionmethod option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for creating an inbox forwarder *)
let create (forward_to_recipients : string list) : t = {
    field = None;
    _match = None;
    forward_to_recipients = forward_to_recipients;
    should = None;
    match_options = None;
    attachment_text_extraction_method = None;
}

