(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_phone_provisioning_job_options.t : Create an advanced phone provisioning job
 *)

type t = {
    phone_country: Enums.phonecountry;
    phone_variant: Enums.phonevariant option [@default None];
    items: Create_phone_provisioning_job_item_options.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Create an advanced phone provisioning job *)
let create (phone_country : Enums.phonecountry) (items : Create_phone_provisioning_job_item_options.t list) : t = {
    phone_country = phone_country;
    phone_variant = None;
    items = items;
}

