(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_deliverability_test_options.t : Create a new deliverability/load test
 *)

type t = {
    (* Optional name for the test *)
    name: string option [@default None];
    (* Optional description *)
    description: string option [@default None];
    (* Entity scope to evaluate *)
    scope: Enums.createdeliverabilitytestoptions_scope;
    (* UTC instant when the receive window starts. Defaults to now if omitted. *)
    start_at: string option [@default None];
    (* Optional timeout in seconds after startAt. If not all entities match before timeout the test transitions to FAILED. *)
    max_duration_seconds: int64 option [@default None];
    (* Optional acceptable success threshold percentage (0,100]. If set, a timed-out test can complete successfully when matchedEntities/totalEntities reaches this percentage. *)
    success_threshold_percent: float option [@default None];
    selector: Deliverability_selector_options.t;
    (* One or more expectations to evaluate for each entity *)
    expectations: Deliverability_expectation.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Create a new deliverability/load test *)
let create (scope : Enums.createdeliverabilitytestoptions_scope) (selector : Deliverability_selector_options.t) (expectations : Deliverability_expectation.t list) : t = {
    name = None;
    description = None;
    scope = scope;
    start_at = None;
    max_duration_seconds = None;
    success_threshold_percent = None;
    selector = selector;
    expectations = expectations;
}

