(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Optional providers to request for rendering. Defaults to ESP_DEFAULT_PROVIDERS when set, otherwise GMAIL and OUTLOOK. *)
    providers: Enums.providers list;
    (* Optional flag to request all configured providers in ESP. Defaults to false when omitted *)
    include_all_configured_providers: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    providers = [];
    include_all_configured_providers = None;
}

