(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_inbox_forwarder_options.t : Options for creating an inbox forwarder
 *)

type t = {
    (* Field to match against to trigger inbox forwarding for inbound email *)
    field: Enums.field;
    (* String or wildcard style match for field specified when evaluating forwarding rules *)
    _match: string;
    (* Email addresses to forward an email to if it matches the field and match criteria of the forwarder *)
    forward_to_recipients: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Options for creating an inbox forwarder *)
let create (field : Enums.field) (_match : string) (forward_to_recipients : string list) : t = {
    field = field;
    _match = _match;
    forward_to_recipients = forward_to_recipients;
}

