(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_webhook_options.t : Options for creating a webhook. Webhooks can be attached to inboxes and MailSlurp will POST a webhook payload to the URL specified whenever the inbox receives an email. Webhooks are great for processing many inbound emails.
 *)

type t = {
    basic_auth: Basic_auth_options.t option [@default None];
    (* Optional webhook event name. Default is `EMAIL_RECEIVED`. Payload differ according to the webhook event name. *)
    event_name: Enums.eventname option [@default None];
    (* Optional name for the webhook *)
    name: string option [@default None];
    (* Public URL on your server that MailSlurp can post WebhookNotification payload to when an email is received. The payload of the submitted JSON is described by https://api.mailslurp.com/schemas/webhook-payload *)
    url: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for creating a webhook. Webhooks can be attached to inboxes and MailSlurp will POST a webhook payload to the URL specified whenever the inbox receives an email. Webhooks are great for processing many inbound emails. *)
let create () : t = {
    basic_auth = None;
    event_name = None;
    name = None;
    url = None;
}

