(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_connector_imap_connection_options.t : Options for IMAP connection to external email inbox. Allows syncing emails via IMAP.
 *)

type t = {
    imap_ssl: bool option [@default None];
    imap_username: string option [@default None];
    imap_password: string option [@default None];
    (* Optional folder to select during IMAP connection *)
    select_folder: string option [@default None];
    search_terms: string option [@default None];
    (* IMAP server port *)
    imap_port: int32 option [@default None];
    (* IMAP server host *)
    imap_host: string;
    (* IMAP server enabled *)
    enabled: bool option [@default None];
    start_tls: bool option [@default None];
    proxy_enabled: bool option [@default None];
    proxy_port: int32 option [@default None];
    proxy_host: string option [@default None];
    local_host_name: string option [@default None];
    (* List of IMAP mechanisms *)
    mechanisms: string list;
    ssl_trust: string option [@default None];
    (* List of SSL protocols *)
    ssl_protocols: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Options for IMAP connection to external email inbox. Allows syncing emails via IMAP. *)
let create (imap_host : string) : t = {
    imap_ssl = None;
    imap_username = None;
    imap_password = None;
    select_folder = None;
    search_terms = None;
    imap_port = None;
    imap_host = imap_host;
    enabled = None;
    start_tls = None;
    proxy_enabled = None;
    proxy_port = None;
    proxy_host = None;
    local_host_name = None;
    mechanisms = [];
    ssl_trust = None;
    ssl_protocols = [];
}

