(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    connector_type: Enums.connectortype[@default `IMAP];
    connector_auth_type: Enums.connectorauthtype[@default `PLAIN_TEXT];
    imap_settings: Create_connector_imap_options.t option [@default None];
    inbox_id: string option [@default None];
    sync_enabled: bool;
    sync_schedule_type: Enums.syncscheduletype[@default `INTERVAL];
    sync_interval: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (connector_type : Enums.connectortype) (connector_auth_type : Enums.connectorauthtype) (sync_enabled : bool) (sync_schedule_type : Enums.syncscheduletype) : t = {
    connector_type = connector_type;
    connector_auth_type = connector_auth_type;
    imap_settings = None;
    inbox_id = None;
    sync_enabled = sync_enabled;
    sync_schedule_type = sync_schedule_type;
    sync_interval = None;
}

