(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    user_id: string;
    sent_id: string option [@default None];
    remote_mta_ip: string option [@default None];
    inbox_id: string option [@default None];
    reporting_mta: string option [@default None];
    recipients: string list;
    smtp_response: string option [@default None];
    smtp_status_code: int32 option [@default None];
    processing_time_millis: int64 option [@default None];
    received: string option [@default None];
    subject: string option [@default None];
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    user_id = user_id;
    sent_id = None;
    remote_mta_ip = None;
    inbox_id = None;
    reporting_mta = None;
    recipients = [];
    smtp_response = None;
    smtp_status_code = None;
    processing_time_millis = None;
    received = None;
    subject = None;
    created_at = created_at;
    updated_at = updated_at;
}

