(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_simulation_job_dto.t : Deliverability simulation job status
 *)

type t = {
    id: string;
    test_id: string;
    scope: Enums.createdeliverabilitytestoptions_scope;
    status: Enums.deliverabilitysimulationjobdto_status;
    created_at: string;
    updated_at: string;
    started_at: string option [@default None];
    completed_at: string option [@default None];
    total_targets: int64;
    total_planned_sends: int64;
    next_send_index: int64;
    sent_count: int64;
    success_count: int64;
    failure_count: int64;
    progress_percent: float;
    active_target_label: string option [@default None];
    estimated_remaining_ms: int64 option [@default None];
    config_snapshot: Deliverability_simulation_job_config_dto.t;
    error_summary: Deliverability_simulation_job_error_summary_dto.t;
} [@@deriving yojson { strict = false }, show ];;

(** Deliverability simulation job status *)
let create (id : string) (test_id : string) (scope : Enums.createdeliverabilitytestoptions_scope) (status : Enums.deliverabilitysimulationjobdto_status) (created_at : string) (updated_at : string) (total_targets : int64) (total_planned_sends : int64) (next_send_index : int64) (sent_count : int64) (success_count : int64) (failure_count : int64) (progress_percent : float) (config_snapshot : Deliverability_simulation_job_config_dto.t) (error_summary : Deliverability_simulation_job_error_summary_dto.t) : t = {
    id = id;
    test_id = test_id;
    scope = scope;
    status = status;
    created_at = created_at;
    updated_at = updated_at;
    started_at = None;
    completed_at = None;
    total_targets = total_targets;
    total_planned_sends = total_planned_sends;
    next_send_index = next_send_index;
    sent_count = sent_count;
    success_count = success_count;
    failure_count = failure_count;
    progress_percent = progress_percent;
    active_target_label = None;
    estimated_remaining_ms = None;
    config_snapshot = config_snapshot;
    error_summary = error_summary;
}

