(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_failure_phone_dimension_hotspot_dto.t : Most common failing phone country/variant dimensions
 *)

type t = {
    phone_country: Enums.phonecountry option [@default None];
    phone_variant: Enums.phonevariant option [@default None];
    failed_run_count: int64;
    total_run_count: int64;
    failure_rate_percentage: float;
} [@@deriving yojson { strict = false }, show ];;

(** Most common failing phone country/variant dimensions *)
let create (failed_run_count : int64) (total_run_count : int64) (failure_rate_percentage : float) : t = {
    phone_country = None;
    phone_variant = None;
    failed_run_count = failed_run_count;
    total_run_count = total_run_count;
    failure_rate_percentage = failure_rate_percentage;
}

