(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_analytics_series_dto.t : Deliverability analytics response for time-range comparison
 *)

type t = {
    since: string;
    before: string;
    scope: Enums.createdeliverabilitytestoptions_scope option [@default None];
    bucket: Enums.bucket;
    summary: Deliverability_analytics_summary_dto.t;
    runs: Deliverability_analytics_run_dto.t list;
    points: Deliverability_analytics_series_point_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Deliverability analytics response for time-range comparison *)
let create (since : string) (before : string) (bucket : Enums.bucket) (summary : Deliverability_analytics_summary_dto.t) (runs : Deliverability_analytics_run_dto.t list) (points : Deliverability_analytics_series_point_dto.t list) : t = {
    since = since;
    before = before;
    scope = None;
    bucket = bucket;
    summary = summary;
    runs = runs;
    points = points;
}

