(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_simulation_job_error_summary_dto.t : Simulation error summary
 *)

type t = {
    last_error: string option [@default None];
    top_errors: Deliverability_simulation_job_top_error_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Simulation error summary *)
let create (top_errors : Deliverability_simulation_job_top_error_dto.t list) : t = {
    last_error = None;
    top_errors = top_errors;
}

