(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_analytics_summary_dto.t : Aggregated deliverability metrics for a given set of runs
 *)

type t = {
    total_runs: int64;
    complete_runs: int64;
    failed_runs: int64;
    stopped_runs: int64;
    running_runs: int64;
    scheduled_runs: int64;
    paused_runs: int64;
    created_runs: int64;
    threshold_configured_runs: int64;
    threshold_met_runs: int64;
    average_completion_percentage: float;
    average_matched_entities: float;
    average_unmatched_entities: float;
} [@@deriving yojson { strict = false }, show ];;

(** Aggregated deliverability metrics for a given set of runs *)
let create (total_runs : int64) (complete_runs : int64) (failed_runs : int64) (stopped_runs : int64) (running_runs : int64) (scheduled_runs : int64) (paused_runs : int64) (created_runs : int64) (threshold_configured_runs : int64) (threshold_met_runs : int64) (average_completion_percentage : float) (average_matched_entities : float) (average_unmatched_entities : float) : t = {
    total_runs = total_runs;
    complete_runs = complete_runs;
    failed_runs = failed_runs;
    stopped_runs = stopped_runs;
    running_runs = running_runs;
    scheduled_runs = scheduled_runs;
    paused_runs = paused_runs;
    created_runs = created_runs;
    threshold_configured_runs = threshold_configured_runs;
    threshold_met_runs = threshold_met_runs;
    average_completion_percentage = average_completion_percentage;
    average_matched_entities = average_matched_entities;
    average_unmatched_entities = average_unmatched_entities;
}

