(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_test_page_dto.t : Paged list of deliverability tests
 *)

type t = {
    content: Deliverability_test_dto.t list;
    page: int32;
    size: int32;
    total_elements: int64;
    total_pages: int32;
} [@@deriving yojson { strict = false }, show ];;

(** Paged list of deliverability tests *)
let create (content : Deliverability_test_dto.t list) (page : int32) (size : int32) (total_elements : int64) (total_pages : int32) : t = {
    content = content;
    page = page;
    size = size;
    total_elements = total_elements;
    total_pages = total_pages;
}

