(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_simulation_job_top_error_dto.t : Top simulation error summary item
 *)

type t = {
    message: string;
    count: int64;
} [@@deriving yojson { strict = false }, show ];;

(** Top simulation error summary item *)
let create (message : string) (count : int64) : t = {
    message = message;
    count = count;
}

