(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Deliverability_failure_entity_hotspot_dto.t : Most common failing entity across deliverability runs
 *)

type t = {
    entity_id: string;
    entity_label: string;
    scope: Enums.createdeliverabilitytestoptions_scope;
    phone_country: Enums.phonecountry option [@default None];
    phone_variant: Enums.phonevariant option [@default None];
    failed_run_count: int64;
    total_run_count: int64;
    failure_rate_percentage: float;
} [@@deriving yojson { strict = false }, show ];;

(** Most common failing entity across deliverability runs *)
let create (entity_id : string) (entity_label : string) (scope : Enums.createdeliverabilitytestoptions_scope) (failed_run_count : int64) (total_run_count : int64) (failure_rate_percentage : float) : t = {
    entity_id = entity_id;
    entity_label = entity_label;
    scope = scope;
    phone_country = None;
    phone_variant = None;
    failed_run_count = failed_run_count;
    total_run_count = total_run_count;
    failure_rate_percentage = failure_rate_percentage;
}

