(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    feedback_id: string;
    user_id: string;
    source: Enums.source;
    category: Enums.category;
    status: Enums.updatedevicepreviewfeedbackoptions_status;
    rating: int32 option [@default None];
    run_id: string option [@default None];
    target_id: string option [@default None];
    screenshot_id: string option [@default None];
    provider: Enums.providers option [@default None];
    title: string option [@default None];
    comment: string option [@default None];
    internal_note: string option [@default None];
    session_id: string option [@default None];
    live_view_url: string option [@default None];
    metadata: (string * string) list;
    created_at: string option [@default None];
    updated_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (feedback_id : string) (user_id : string) (source : Enums.source) (category : Enums.category) (status : Enums.updatedevicepreviewfeedbackoptions_status) : t = {
    feedback_id = feedback_id;
    user_id = user_id;
    source = source;
    category = category;
    status = status;
    rating = None;
    run_id = None;
    target_id = None;
    screenshot_id = None;
    provider = None;
    title = None;
    comment = None;
    internal_note = None;
    session_id = None;
    live_view_url = None;
    metadata = [];
    created_at = None;
    updated_at = None;
}

