(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    run_id: string;
    provider: string option [@default None];
    client_profile: string option [@default None];
    device_type: string option [@default None];
    browser_family: string option [@default None];
    platform: string option [@default None];
    color_scheme: string option [@default None];
    status: Enums.devicepreviewtargetdto_status option [@default None];
    failure_code: string option [@default None];
    primary_screenshot_id: string option [@default None];
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (run_id : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    run_id = run_id;
    provider = None;
    client_profile = None;
    device_type = None;
    browser_family = None;
    platform = None;
    color_scheme = None;
    status = None;
    failure_code = None;
    primary_screenshot_id = None;
    created_at = created_at;
    updated_at = updated_at;
}

