(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Dns_lookups_options.t : Options for multiple DNS queries
 *)

type t = {
    lookups: Dns_lookup_options.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Options for multiple DNS queries *)
let create (lookups : Dns_lookup_options.t list) : t = {
    lookups = lookups;
}

