(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    monitor: Domain_monitor_dto.t;
    latest_run: Domain_monitor_run_dto.t option [@default None];
    insights: Domain_monitor_insights_dto.t;
    auth_stack: Check_email_auth_stack_results.t;
} [@@deriving yojson { strict = false }, show ];;

let create (monitor : Domain_monitor_dto.t) (insights : Domain_monitor_insights_dto.t) (auth_stack : Check_email_auth_stack_results.t) : t = {
    monitor = monitor;
    latest_run = None;
    insights = insights;
    auth_stack = auth_stack;
}

