(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    baseline: Domain_monitor_run_dto.t;
    current: Domain_monitor_run_dto.t;
    health_score_delta: int32;
    status_changed: bool;
    passing_checks_delta: int32;
    failing_checks_delta: int32;
    spf_changed: bool;
    dmarc_changed: bool;
    dmarc_enforced_changed: bool;
    mx_changed: bool;
    added_insights: string list;
    removed_insights: string list;
} [@@deriving yojson { strict = false }, show ];;

let create (baseline : Domain_monitor_run_dto.t) (current : Domain_monitor_run_dto.t) (health_score_delta : int32) (status_changed : bool) (passing_checks_delta : int32) (failing_checks_delta : int32) (spf_changed : bool) (dmarc_changed : bool) (dmarc_enforced_changed : bool) (mx_changed : bool) (added_insights : string list) (removed_insights : string list) : t = {
    baseline = baseline;
    current = current;
    health_score_delta = health_score_delta;
    status_changed = status_changed;
    passing_checks_delta = passing_checks_delta;
    failing_checks_delta = failing_checks_delta;
    spf_changed = spf_changed;
    dmarc_changed = dmarc_changed;
    dmarc_enforced_changed = dmarc_enforced_changed;
    mx_changed = mx_changed;
    added_insights = added_insights;
    removed_insights = removed_insights;
}

