(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    monitor_id: string;
    user_id: string;
    _type: Enums.createdomainmonitoralertsinkoptions_type;
    target: string;
    severity_threshold: Enums.severitythreshold;
    enabled: bool;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (monitor_id : string) (user_id : string) (_type : Enums.createdomainmonitoralertsinkoptions_type) (target : string) (severity_threshold : Enums.severitythreshold) (enabled : bool) (created_at : string) (updated_at : string) : t = {
    id = id;
    monitor_id = monitor_id;
    user_id = user_id;
    _type = _type;
    target = target;
    severity_threshold = severity_threshold;
    enabled = enabled;
    created_at = created_at;
    updated_at = updated_at;
}

