(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Domain_preview.t : Preview object for domain entity
 *)

type t = {
    catch_all_inbox_id: string option [@default None];
    created_at: string;
    domain: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Preview object for domain entity *)
let create (created_at : string) (domain : string) (id : string) : t = {
    catch_all_inbox_id = None;
    created_at = created_at;
    domain = domain;
    id = id;
}

