(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Domain_dto.t : Domain plus verification records and status
 *)

type t = {
    (* The optional catch all inbox that will receive emails sent to the domain that cannot be matched. *)
    catch_all_inbox_id: string option [@default None];
    created_at: string;
    (* Unique token DKIM tokens *)
    dkim_tokens: string list;
    (* Custom domain name *)
    domain: string option [@default None];
    (* List of DNS domain name records (C, MX, TXT) etc that you must add to the DNS server associated with your domain provider. *)
    domain_name_records: Domain_name_record.t list;
    id: string;
    (* Whether domain has been verified or not. If the domain is not verified after 72 hours there is most likely an issue with the domains DNS records. *)
    is_verified: bool option [@default None];
    updated_at: string;
    user_id: string;
    (* Verification tokens *)
    verification_token: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Domain plus verification records and status *)
let create (created_at : string) (id : string) (updated_at : string) (user_id : string) : t = {
    catch_all_inbox_id = None;
    created_at = created_at;
    dkim_tokens = [];
    domain = None;
    domain_name_records = [];
    id = id;
    is_verified = None;
    updated_at = updated_at;
    user_id = user_id;
    verification_token = None;
}

