(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Domain_preview.t : Preview object for domain entity
 *)

type t = {
    catch_all_inbox_id: string option [@default None];
    created_at: string;
    domain: string;
    domain_type: Enums.domaintype;
    id: string;
    is_verified: bool;
} [@@deriving yojson { strict = false }, show ];;

(** Preview object for domain entity *)
let create (created_at : string) (domain : string) (domain_type : Enums.domaintype) (id : string) (is_verified : bool) : t = {
    catch_all_inbox_id = None;
    created_at = created_at;
    domain = domain;
    domain_type = domain_type;
    id = id;
    is_verified = is_verified;
}

