(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Domain_region_groups_dto.t : Grouped available domains including account-region policy status.
 *)

type t = {
    domain_groups: Domain_region_group.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Grouped available domains including account-region policy status. *)
let create (domain_groups : Domain_region_group.t list) : t = {
    domain_groups = domain_groups;
}

