(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Download_attachment_dto.t : Content of attachment
 *)

type t = {
    (* Base64 encoded string of attachment bytes. Decode the base64 encoded string to get the raw contents. If the file has a content type such as `text/html` you can read the contents directly by converting it to string using `utf-8` encoding. *)
    base64_file_contents: string;
    (* Content type of attachment. Examples are `image/png`, `application/msword`, `text/csv` etc. *)
    content_type: string;
    (* Size in bytes of attachment content *)
    size_bytes: int64;
} [@@deriving yojson { strict = false }, show ];;

(** Content of attachment *)
let create (base64_file_contents : string) (content_type : string) (size_bytes : int64) : t = {
    base64_file_contents = base64_file_contents;
    content_type = content_type;
    size_bytes = size_bytes;
}

