(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_audit_url_issue.t : A single URL issue discovered during email audit checks
 *)

type t = {
    url: string;
    status_code: int32 option [@default None];
    message: string;
} [@@deriving yojson { strict = false }, show ];;

(** A single URL issue discovered during email audit checks *)
let create (url : string) (message : string) : t = {
    url = url;
    status_code = None;
    message = message;
}

