(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_preview.t : Preview of an email message. For full message (including body and attachments) call the `getEmail` or other email endpoints with the provided email ID.
 *)

type t = {
    (* ID of the email entity *)
    id: string;
    (* ID of the inbox that received the email *)
    inbox_id: string option [@default None];
    (* ID of the domain that received the email *)
    domain_id: string option [@default None];
    (* The subject line of the email message as specified by SMTP subject header *)
    subject: string option [@default None];
    (* List of `To` recipient email addresses that the email was addressed to. See recipients object for names. *)
    _to: string list;
    (* Who the email was sent from. An email address - see fromName for the sender name. *)
    from: string option [@default None];
    (* List of `BCC` recipients email addresses that the email was addressed to. See recipients object for names. *)
    bcc: string list;
    (* List of `CC` recipients email addresses that the email was addressed to. See recipients object for names. *)
    cc: string list;
    (* When was the email received by MailSlurp *)
    created_at: string;
    (* Read flag. Has the email ever been viewed in the dashboard or fetched via the API with a hydrated body? If so the email is marked as read. Paginated results do not affect read status. Read status is different to email opened event as it depends on your own account accessing the email. Email opened is determined by tracking pixels sent to other uses if enable during sending. You can listened for both email read and email opened events using webhooks. *)
    read: bool;
    (* List of IDs of attachments found in the email. Use these IDs with the Inbox and Email Controllers to download attachments and attachment meta data such as filesize, name, extension. *)
    attachments: string list;
    (* MailSlurp thread ID for email chain that enables lookup for In-Reply-To and References fields. *)
    thread_id: string option [@default None];
    (* RFC 5322 Message-ID header value without angle brackets. *)
    message_id: string option [@default None];
    (* Parsed value of In-Reply-To header. A Message-ID in a thread. *)
    in_reply_to: string option [@default None];
    sender: Sender.t option [@default None];
    recipients: Email_recipients.t option [@default None];
    favourite: bool option [@default None];
    body_part_content_types: string list;
    plus_address: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Preview of an email message. For full message (including body and attachments) call the `getEmail` or other email endpoints with the provided email ID. *)
let create (id : string) (_to : string list option) (created_at : string) (read : bool) : t = {
    id = id;
    inbox_id = None;
    domain_id = None;
    subject = None;
    _to = _to;
    from = None;
    bcc = [];
    cc = [];
    created_at = created_at;
    read = read;
    attachments = [];
    thread_id = None;
    message_id = None;
    in_reply_to = None;
    sender = None;
    recipients = None;
    favourite = None;
    body_part_content_types = [];
    plus_address = None;
}

