(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_analysis.t : Analysis result for email. Each verdict property is a string PASS|FAIL|GRAY or dynamic error message
 *)

type t = {
    (* Verdict of DomainKeys Identified Mail analysis *)
    dkim_verdict: string option [@default None];
    (* Verdict of Domain-based Message Authentication Reporting and Conformance analysis *)
    dmarc_verdict: string option [@default None];
    (* Verdict of spam ranking analysis *)
    spam_verdict: string option [@default None];
    (* Verdict of Send Policy Framework record spoofing analysis *)
    spf_verdict: string option [@default None];
    (* Verdict of virus scan analysis *)
    virus_verdict: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Analysis result for email. Each verdict property is a string PASS|FAIL|GRAY or dynamic error message *)
let create () : t = {
    dkim_verdict = None;
    dmarc_verdict = None;
    spam_verdict = None;
    spf_verdict = None;
    virus_verdict = None;
}

