(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    from: string option [@default None];
    by: string option [@default None];
    with_value: string option [@default None];
    timestamp: string option [@default None];
    delay_ms: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    from = None;
    by = None;
    with_value = None;
    timestamp = None;
    delay_ms = None;
}

