(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_intelligence_score_breakdown_dto.t : Penalty breakdown used to compute email intelligence score.
 *)

type t = {
    randomness_penalty: int32;
    free_provider_penalty: int32;
    https_website_penalty: int32;
    dns_penalty: int32;
    domain_age_penalty: int32;
    email_validation_penalty: int32;
    total_penalty: int32;
} [@@deriving yojson { strict = false }, show ];;

(** Penalty breakdown used to compute email intelligence score. *)
let create (randomness_penalty : int32) (free_provider_penalty : int32) (https_website_penalty : int32) (dns_penalty : int32) (domain_age_penalty : int32) (email_validation_penalty : int32) (total_penalty : int32) : t = {
    randomness_penalty = randomness_penalty;
    free_provider_penalty = free_provider_penalty;
    https_website_penalty = https_website_penalty;
    dns_penalty = dns_penalty;
    domain_age_penalty = domain_age_penalty;
    email_validation_penalty = email_validation_penalty;
    total_penalty = total_penalty;
}

