(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_preview_urls.t : URLs for email body
 *)

type t = {
    raw_smtp_message_url: string;
    plain_html_body_url: string;
} [@@deriving yojson { strict = false }, show ];;

(** URLs for email body *)
let create (raw_smtp_message_url : string) (plain_html_body_url : string) : t = {
    raw_smtp_message_url = raw_smtp_message_url;
    plain_html_body_url = plain_html_body_url;
}

