(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_intelligence_tests_options.t : Optional test toggles for email intelligence scoring.
 *)

type t = {
    (* Check local-part randomness for email inputs. *)
    check_random_local_part: bool option [@default None];
    (* Check if domain is a known free email provider. *)
    check_free_provider: bool option [@default None];
    (* Check if the domain has a reachable HTTPS website. *)
    check_https_website: bool option [@default None];
    (* Check DNS records (A, MX, SOA) for the domain. *)
    check_dns: bool option [@default None];
    (* Derive a domain age hint from DNS SOA serial when possible. *)
    check_domain_age_hint: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Optional test toggles for email intelligence scoring. *)
let create () : t = {
    check_random_local_part = None;
    check_free_provider = None;
    check_https_website = None;
    check_dns = None;
    check_domain_age_hint = None;
}

