(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email_intelligence_options.t : Request options for running email intelligence checks on one or more inputs.
 *)

type t = {
    (* Email addresses or domains to score. *)
    targets: string list;
    (* Zero-based page index for processing a subset of the target list. *)
    page: int32 option [@default None];
    (* Page size for processing a subset of the target list. *)
    size: int32 option [@default None];
    (* Ignore cached intelligence values and force recomputation. *)
    ignore_cache: bool option [@default None];
    (* Also run mailbox safety verification using the existing verification client for email inputs. *)
    include_email_validation: bool option [@default None];
    tests: Email_intelligence_tests_options.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Request options for running email intelligence checks on one or more inputs. *)
let create (targets : string list) : t = {
    targets = targets;
    page = None;
    size = None;
    ignore_cache = None;
    include_email_validation = None;
    tests = None;
}

