(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    feature: Enums.feature;
    title: string option [@default None];
    description: string option [@default None];
    category: Enums.emailfeaturecategoryname_slug option [@default None];
    notes: string option [@default None];
    notes_numbers: (string * string) list;
    feature_statistics: Email_feature_family_statistics.t list;
    statuses: Enums.statuses list;
} [@@deriving yojson { strict = false }, show ];;

let create (feature : Enums.feature) (statuses : Enums.statuses list) : t = {
    feature = feature;
    title = None;
    description = None;
    category = None;
    notes = None;
    notes_numbers = [];
    feature_statistics = [];
    statuses = statuses;
}

