(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    version: string;
    support_flags: Email_feature_support_flags.t;
} [@@deriving yojson { strict = false }, show ];;

let create (version : string) (support_flags : Email_feature_support_flags.t) : t = {
    version = version;
    support_flags = support_flags;
}

