(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    severity: Enums.entityeventitemprojection_severity;
    event_type: Enums.entityeventitemprojection_eventtype;
    inbox_id: string option [@default None];
    phone_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (severity : Enums.entityeventitemprojection_severity) (event_type : Enums.entityeventitemprojection_eventtype) : t = {
    id = id;
    severity = severity;
    event_type = event_type;
    inbox_id = None;
    phone_id = None;
}

