(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    event_type: Enums.eventtype;
    inbox_id: string option [@default None];
    phone_id: string option [@default None];
    id: string;
    severity: Enums.entityeventitemprojection_severity;
} [@@deriving yojson { strict = false }, show ];;

let create (event_type : Enums.eventtype) (id : string) (severity : Enums.entityeventitemprojection_severity) : t = {
    event_type = event_type;
    inbox_id = None;
    phone_id = None;
    id = id;
    severity = severity;
}

