(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Export_link.t : Export download link
 *)

type t = {
    download_link: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Export download link *)
let create () : t = {
    download_link = None;
}

