(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    ai_transform_id: string option [@default None];
    ai_mapping_id: string option [@default None];
    flatten_arrays: bool;
    since: string option [@default None];
    before: string option [@default None];
    format: Enums.format;
    inbox_id: string option [@default None];
    phone_id: string option [@default None];
    email_id: string option [@default None];
    sms_id: string option [@default None];
    attachment_id: string option [@default None];
    include_meta_data: bool;
    delimiter: string option [@default None];
    array_separator: string option [@default None];
    include_meta_data_columns: string list;
} [@@deriving yojson { strict = false }, show ];;

let create (flatten_arrays : bool) (format : Enums.format) (include_meta_data : bool) : t = {
    ai_transform_id = None;
    ai_mapping_id = None;
    flatten_arrays = flatten_arrays;
    since = None;
    before = None;
    format = format;
    inbox_id = None;
    phone_id = None;
    email_id = None;
    sms_id = None;
    attachment_id = None;
    include_meta_data = include_meta_data;
    delimiter = None;
    array_separator = None;
    include_meta_data_columns = [];
}

