(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Extract_attachment_text_options.t : Options for extracting text from an attachment. Choose a method and whether fallback is allowed.
 *)

type t = {
    (* Method for extracting text from attachments. OCR/LLM methods are reserved for advanced extraction. *)
    _method: Enums.extractattachmenttextoptions_method option [@default None];
    (* Allow fallback to native extraction when the selected method is unavailable. *)
    allow_fallback: bool option [@default None];
    (* Maximum bytes to read from attachment for native text extraction. *)
    max_bytes: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for extracting text from an attachment. Choose a method and whether fallback is allowed. *)
let create () : t = {
    _method = None;
    allow_fallback = None;
    max_bytes = None;
}

