(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Extract_codes_options.t : Options for extracting verification codes from email or SMS content. Use method to control extraction strategy and allowFallback to control strictness.
 *)

type t = {
    (* Extraction strategy for verification codes. Unsupported strategies may fall back when allowFallback is true. *)
    _method: Enums.extractcodesoptions_method option [@default None];
    (* Allow fallback to deterministic pattern extraction when the selected method is unavailable. *)
    allow_fallback: bool option [@default None];
    (* Minimum code length to consider. Typical OTP values are between 4 and 8 characters. *)
    min_length: int32 option [@default None];
    (* Maximum code length to consider. *)
    max_length: int32 option [@default None];
    (* Maximum number of code candidates to return. Best candidate is also returned separately. *)
    max_candidates: int32 option [@default None];
    (* Optional custom regex patterns for code extraction. Each pattern should have either one capture group for the code or match the full code directly. *)
    custom_patterns: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Options for extracting verification codes from email or SMS content. Use method to control extraction strategy and allowFallback to control strictness. *)
let create () : t = {
    _method = None;
    allow_fallback = None;
    min_length = None;
    max_length = None;
    max_candidates = None;
    custom_patterns = [];
}

