(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    email_address: string;
    sender: Sender.t option [@default None];
    recipients: Email_recipients.t option [@default None];
    attachment_names: string list;
    subject: string option [@default None];
    preview: string option [@default None];
    (* use read content endpoints instead *)
    body: string;
    seen: bool;
    created_at: string;
    content_type: string;
    body_url: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (email_address : string) (attachment_names : string list) (body : string) (seen : bool) (created_at : string) (content_type : string) (body_url : string) : t = {
    id = id;
    email_address = email_address;
    sender = None;
    recipients = None;
    attachment_names = attachment_names;
    subject = None;
    preview = None;
    body = body;
    seen = seen;
    created_at = created_at;
    content_type = content_type;
    body_url = body_url;
}

