(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Forward_email_options.t : Options for forwarding an email
 *)

type t = {
    (* Optional bcc recipients *)
    bcc: string list;
    (* Optional cc recipients *)
    cc: string list;
    (* Optional from override *)
    from: string option [@default None];
    (* Subject for forwarded email *)
    subject: string option [@default None];
    (* To recipients for forwarded email *)
    _to: string list;
    (* Optionally use inbox name as display name for sender email address *)
    use_inbox_name: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for forwarding an email *)
let create () : t = {
    bcc = [];
    cc = [];
    from = None;
    subject = None;
    _to = [];
    use_inbox_name = None;
}

