(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Generate_structured_content_attachment_options.t : Options for generating structured content output from an attachment
 *)

type t = {
    (* Attachment ID to read and pass to AI *)
    attachment_id: string;
    (* Optional instructions for the AI to follow. Try to be precise and clear. You can include examples and hints. *)
    instructions: string option [@default None];
    output_schema: Structured_output_schema.t option [@default None];
    (* ID of transformer to apply *)
    transform_id: string option [@default None];
    (* Optional email ID for more context *)
    email_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for generating structured content output from an attachment *)
let create (attachment_id : string) : t = {
    attachment_id = attachment_id;
    instructions = None;
    output_schema = None;
    transform_id = None;
    email_id = None;
}

