(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    reporting_addresses: string list;
    reporting_url: string option [@default None];
    host: string;
    version: Enums.version[@default `TLSRPTv1];
    ttl: int32;
} [@@deriving yojson { strict = false }, show ];;

let create (reporting_addresses : string list) (host : string) (version : Enums.version) (ttl : int32) : t = {
    reporting_addresses = reporting_addresses;
    reporting_url = None;
    host = host;
    version = version;
    ttl = ttl;
}

