(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    group: Group_dto.t;
    contacts: Contact_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (group : Group_dto.t) (contacts : Contact_dto.t list) : t = {
    group = group;
    contacts = contacts;
}

