(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string;
    id: string;
    created_at: string;
    description: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) (id : string) (created_at : string) : t = {
    name = name;
    id = id;
    created_at = created_at;
    description = None;
}

