(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Guest_portal_user_projection.t : Representation of a guest portal user
 *)

type t = {
    username: string;
    updated_at: string;
    user_id: string;
    email_address: string option [@default None];
    inbox_id: string option [@default None];
    created_at: string;
    portal_id: string;
    name: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Representation of a guest portal user *)
let create (username : string) (updated_at : string) (user_id : string) (created_at : string) (portal_id : string) (id : string) : t = {
    username = username;
    updated_at = updated_at;
    user_id = user_id;
    email_address = None;
    inbox_id = None;
    created_at = created_at;
    portal_id = portal_id;
    name = None;
    id = id;
}

