(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Imap_smtp_access_details.t : Access details for inbox using SMTP or IMAP
 *)

type t = {
    (* SMTP server host domain *)
    smtp_server_host: string;
    (* SMTP server host port *)
    smtp_server_port: int32;
    (* SMTP username for login *)
    smtp_username: string;
    (* SMTP  for login *)
    smtp_password: string;
    (* IMAP server host domain *)
    imap_server_host: string;
    (* IMAP server host port *)
    imap_server_port: int32;
    (* IMAP username for login *)
    imap_username: string;
    (* IMAP password for login *)
    imap_password: string;
} [@@deriving yojson { strict = false }, show ];;

(** Access details for inbox using SMTP or IMAP *)
let create (smtp_server_host : string) (smtp_server_port : int32) (smtp_username : string) (smtp_password : string) (imap_server_host : string) (imap_server_port : int32) (imap_username : string) (imap_password : string) : t = {
    smtp_server_host = smtp_server_host;
    smtp_server_port = smtp_server_port;
    smtp_username = smtp_username;
    smtp_password = smtp_password;
    imap_server_host = imap_server_host;
    imap_server_port = imap_server_port;
    imap_username = imap_username;
    imap_password = imap_password;
}

