(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Imap_server_search_options.t : IMAP server search options
 *)

type t = {
    seq_num: string option [@default None];
    uid: string option [@default None];
    since: string option [@default None];
    before: string option [@default None];
    sent_since: string option [@default None];
    sent_before: string option [@default None];
    header: (string * string list) list;
    body: string list;
    text: string list;
    with_flags: string list;
    without_flags: string list;
} [@@deriving yojson { strict = false }, show ];;

(** IMAP server search options *)
let create () : t = {
    seq_num = None;
    uid = None;
    since = None;
    before = None;
    sent_since = None;
    sent_before = None;
    header = [];
    body = [];
    text = [];
    with_flags = [];
    without_flags = [];
}

