(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Imap_smtp_access_servers.t : IMAP and SMTP server endpoints for MailSlurp
 *)

type t = {
    imap_server: Server_endpoints.t;
    secure_imap_server: Server_endpoints.t;
    smtp_server: Server_endpoints.t;
    secure_smtp_server: Server_endpoints.t;
} [@@deriving yojson { strict = false }, show ];;

(** IMAP and SMTP server endpoints for MailSlurp *)
let create (imap_server : Server_endpoints.t) (secure_imap_server : Server_endpoints.t) (smtp_server : Server_endpoints.t) (secure_smtp_server : Server_endpoints.t) : t = {
    imap_server = imap_server;
    secure_imap_server = secure_imap_server;
    smtp_server = smtp_server;
    secure_smtp_server = secure_smtp_server;
}

