(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Imap_access_details.t : Access details for inbox using IMAP
 *)

type t = {
    (* Secure TLS IMAP server host domain *)
    secure_imap_server_host: string;
    (* Secure TLS IMAP server host port *)
    secure_imap_server_port: int32;
    (* Secure TLS IMAP username for login *)
    secure_imap_username: string;
    (* Secure TLS IMAP password for login *)
    secure_imap_password: string;
    (* IMAP server host domain *)
    imap_server_host: string;
    (* IMAP server host port *)
    imap_server_port: int32;
    (* IMAP username for login *)
    imap_username: string;
    (* IMAP password for login *)
    imap_password: string;
    (* IMAP mailbox to SELECT *)
    imap_mailbox: string;
} [@@deriving yojson { strict = false }, show ];;

(** Access details for inbox using IMAP *)
let create (secure_imap_server_host : string) (secure_imap_server_port : int32) (secure_imap_username : string) (secure_imap_password : string) (imap_server_host : string) (imap_server_port : int32) (imap_username : string) (imap_password : string) (imap_mailbox : string) : t = {
    secure_imap_server_host = secure_imap_server_host;
    secure_imap_server_port = secure_imap_server_port;
    secure_imap_username = secure_imap_username;
    secure_imap_password = secure_imap_password;
    imap_server_host = imap_server_host;
    imap_server_port = imap_server_port;
    imap_username = imap_username;
    imap_password = imap_password;
    imap_mailbox = imap_mailbox;
}

