(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    read: bool option [@default None];
    uid: int64;
    seq_num: int64;
    created_at: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (uid : int64) (seq_num : int64) (created_at : string) (id : string) : t = {
    read = None;
    uid = uid;
    seq_num = seq_num;
    created_at = created_at;
    id = id;
}

