(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Import_email_options.t : Options for importing a raw RFC822/MIME email into a specific inbox. V1 supports MIME-family formats such as `.eml`, `message/rfc822`, and raw MIME bytes. Outlook `.msg`, `mbox`, and `maildir` are not supported in V1.
 *)

type t = {
    (* Base64 encoded RFC822/MIME email contents. This should be the full raw email including headers and body, such as the bytes from an `.eml` file. *)
    raw_email_base64: string;
    (* Optional external identifier for the imported email source. Useful for correlating imports back to another system. *)
    external_id: string option [@default None];
    (* When true the normal inbound receive pipeline runs after persistence, including automations, webhooks, transformers, forwarders, repliers, and related fanout. When false the email is stored only. *)
    run_pipeline: bool option [@default None];
    (* When true MailSlurp rewrites the MIME `Message-ID` header before storing and parsing the email so imported messages do not collide with existing message identities. *)
    override_message_id: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for importing a raw RFC822/MIME email into a specific inbox. V1 supports MIME-family formats such as `.eml`, `message/rfc822`, and raw MIME bytes. Outlook `.msg`, `mbox`, and `maildir` are not supported in V1. *)
let create (raw_email_base64 : string) : t = {
    raw_email_base64 = raw_email_base64;
    external_id = None;
    run_pipeline = None;
    override_message_id = None;
}

