(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Inbox_dto.t : Representation of a MailSlurp inbox. An inbox has an ID and a real email address. Emails can be sent to or from this email address. Inboxes are either `SMTP` or `HTTP` mailboxes. The default, `HTTP` inboxes, use AWS SES to process emails and are best suited as test email accounts and do not support IMAP or POP3. `SMTP` inboxes use a custom mail server at `mx.mailslurp.com` and support SMTP login, IMAP and POP3. Use the `EmailController` or the `InboxController` methods to send and receive emails and attachments. Inboxes may have a description, name, and tags for display purposes. You can also favourite an inbox for easier searching.
 *)

type t = {
    (* ID of the inbox. The ID is a UUID-V4 format string. Use the inboxId for calls to Inbox and Email Controller endpoints. See the emailAddress property for the email address or the inbox. To get emails in an inbox use the WaitFor and Inbox Controller methods `waitForLatestEmail` and `getEmails` methods respectively. Inboxes can be used with aliases to forward emails automatically. *)
    id: string;
    (* ID of user that inbox belongs to *)
    user_id: string option [@default None];
    (* When the inbox was created. Time stamps are in ISO DateTime Format `yyyy-MM-dd'T'HH:mm:ss.SSSXXX` e.g. `2000-10-31T01:30:00.000-05:00`. *)
    created_at: string;
    (* Name of the inbox and used as the sender name when sending emails .Displayed in the dashboard for easier search *)
    name: string option [@default None];
    (* ID of custom domain used by the inbox if any *)
    domain_id: string option [@default None];
    (* Description of an inbox for labelling and searching purposes *)
    description: string option [@default None];
    (* The inbox's email address. Inbox projections and previews may not include the email address. To view the email address fetch the inbox entity directly. Send an email to this address and the inbox will receive and store it for you. Note the email address in MailSlurp match characters exactly and are case sensitive so `+123` additions are considered different addresses. To retrieve the email use the Inbox and Email Controller endpoints with the inbox ID. *)
    email_address: string;
    (* Inbox expiration time. When, if ever, the inbox should expire and be deleted. If null then this inbox is permanent and the emails in it won't be deleted. This is the default behavior unless expiration date is set. If an expiration date is set and the time is reached MailSlurp will expire the inbox and move it to an expired inbox entity. You can still access the emails belonging to it but it can no longer send or receive email. *)
    expires_at: string option [@default None];
    (* Is the inbox a favorite inbox. Make an inbox a favorite is typically done in the dashboard for quick access or filtering *)
    favourite: bool;
    (* Tags that inbox has been tagged with. Tags can be added to inboxes to group different inboxes within an account. You can also search for inboxes by tag in the dashboard UI. *)
    tags: string list;
    (* Type of inbox. HTTP inboxes are faster and better for most cases. SMTP inboxes are more suited for public facing inbound messages (but cannot send). *)
    inbox_type: Enums.inboxtype option [@default None];
    (* Is the inbox readOnly for the caller. Read only means can not be deleted or modified. This flag is present when using team accounts and shared inboxes. *)
    read_only: bool;
    (* Virtual inbox can receive email but will not send emails to real recipients. Will save sent email record but never send an actual email. Perfect for testing mail server actions. *)
    virtual_inbox: bool;
} [@@deriving yojson { strict = false }, show ];;

(** Representation of a MailSlurp inbox. An inbox has an ID and a real email address. Emails can be sent to or from this email address. Inboxes are either `SMTP` or `HTTP` mailboxes. The default, `HTTP` inboxes, use AWS SES to process emails and are best suited as test email accounts and do not support IMAP or POP3. `SMTP` inboxes use a custom mail server at `mx.mailslurp.com` and support SMTP login, IMAP and POP3. Use the `EmailController` or the `InboxController` methods to send and receive emails and attachments. Inboxes may have a description, name, and tags for display purposes. You can also favourite an inbox for easier searching. *)
let create (id : string) (created_at : string) (email_address : string) (favourite : bool) (read_only : bool) (virtual_inbox : bool) : t = {
    id = id;
    user_id = None;
    created_at = created_at;
    name = None;
    domain_id = None;
    description = None;
    email_address = email_address;
    expires_at = None;
    favourite = favourite;
    tags = [];
    inbox_type = None;
    read_only = read_only;
    virtual_inbox = virtual_inbox;
}

