(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    action: Enums.action;
    handler: Enums.handler[@default `EXCEPTION];
    id: string;
    inbox_id: string;
    scope: Enums.scope;
    target: string;
} [@@deriving yojson { strict = false }, show ];;

let create (action : Enums.action) (handler : Enums.handler) (id : string) (inbox_id : string) (scope : Enums.scope) (target : string) : t = {
    action = action;
    handler = handler;
    id = id;
    inbox_id = inbox_id;
    scope = scope;
    target = target;
}

