(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Inbox_id_item.t : Inbox ID and email address pair
 *)

type t = {
    id: string;
    email_address: string;
} [@@deriving yojson { strict = false }, show ];;

(** Inbox ID and email address pair *)
let create (id : string) (email_address : string) : t = {
    id = id;
    email_address = email_address;
}

