(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Inbox_forwarder_test_options.t : Options for testing an inbox forwarder against a value
 *)

type t = {
    (* Simple value to test against the forwarder's simple field/match rule. Required when emailId is not provided. *)
    test_value: string option [@default None];
    (* Optional email ID to evaluate the forwarder using full inbound email content (headers, recipients, and attachments). *)
    email_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for testing an inbox forwarder against a value *)
let create () : t = {
    test_value = None;
    email_id = None;
}

