(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string option [@default None];
    inbox_id: string option [@default None];
    field: Enums.field option [@default None];
    _match: string option [@default None];
    forward_to_recipients: string list;
    created_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    inbox_id = None;
    field = None;
    _match = None;
    forward_to_recipients = [];
    created_at = None;
}

