(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    ai_transform_id: string option [@default None];
    ai_transform_mapping_id: string option [@default None];
    raw_input: string option [@default None];
    entity_id: string option [@default None];
    entity_type: Enums.entitytype option [@default None];
    raw_conditions: string list;
    raw_instructions: string list;
    raw_output_schema: Structured_output_schema.t option [@default None];
    content_selector: Enums.contentselector option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    ai_transform_id = None;
    ai_transform_mapping_id = None;
    raw_input = None;
    entity_id = None;
    entity_type = None;
    raw_conditions = [];
    raw_instructions = [];
    raw_output_schema = None;
    content_selector = None;
}

