(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    url: string;
    response_status: int32 option [@default None];
    severity: Enums.imageissue_severity;
    message: string;
} [@@deriving yojson { strict = false }, show ];;

let create (url : string) (severity : Enums.imageissue_severity) (message : string) : t = {
    url = url;
    response_status = None;
    severity = severity;
    message = message;
}

