(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema List_unsubscribe_recipient_projection.t : List unsubscribe recipient
 *)

type t = {
    created_at: string;
    email_address: string;
    domain_id: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** List unsubscribe recipient *)
let create (created_at : string) (email_address : string) (id : string) : t = {
    created_at = created_at;
    email_address = email_address;
    domain_id = None;
    id = id;
}

