(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Root domain to inspect for SPF *)
    host: string;
} [@@deriving yojson { strict = false }, show ];;

let create (host : string) : t = {
    host = host;
}

