(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* IPv4 or IPv6 address to inspect *)
    ip: string;
    captcha_token: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (ip : string) : t = {
    ip = ip;
    captcha_token = None;
}

