(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Missed_sms_projection.t : Missed SMS projection
 *)

type t = {
    id: string;
    user_id: string;
    created_at: string;
    phone_number: string;
    sid: string;
    from_number: string;
} [@@deriving yojson { strict = false }, show ];;

(** Missed SMS projection *)
let create (id : string) (user_id : string) (created_at : string) (phone_number : string) (sid : string) (from_number : string) : t = {
    id = id;
    user_id = user_id;
    created_at = created_at;
    phone_number = phone_number;
    sid = sid;
    from_number = from_number;
}

