(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Missed_sms_dto.t : Missed SMS
 *)

type t = {
    id: string;
    user_id: string;
    phone_number: string;
    from_number: string;
    to_number: string option [@default None];
    body: string;
    sid: string;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Missed SMS *)
let create (id : string) (user_id : string) (phone_number : string) (from_number : string) (body : string) (sid : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    user_id = user_id;
    phone_number = phone_number;
    from_number = from_number;
    to_number = None;
    body = body;
    sid = sid;
    created_at = created_at;
    updated_at = updated_at;
}

