(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    attachment_count: int32;
    bcc: string list;
    body_excerpt: string option [@default None];
    cc: string list;
    created_at: string;
    from: string option [@default None];
    id: string option [@default None];
    inbox_ids: string list;
    subject: string option [@default None];
    _to: string list;
    updated_at: string;
    user_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (attachment_count : int32) (bcc : string list) (cc : string list) (created_at : string) (inbox_ids : string list) (_to : string list) (updated_at : string) : t = {
    attachment_count = attachment_count;
    bcc = bcc;
    body_excerpt = None;
    cc = cc;
    created_at = created_at;
    from = None;
    id = None;
    inbox_ids = inbox_ids;
    subject = None;
    _to = _to;
    updated_at = updated_at;
    user_id = None;
}

