(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Name_server_record.t : Name Server Record
 *)

type t = {
    raw: string;
    record_type: string;
    priority: string;
    value: string;
} [@@deriving yojson { strict = false }, show ];;

(** Name Server Record *)
let create (raw : string) (record_type : string) (priority : string) (value : string) : t = {
    raw = raw;
    record_type = record_type;
    priority = priority;
    value = value;
}

