(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    email_address: string;
    company_name: string option [@default None];
    send_opt_in_options: Send_opt_in_consent_email_options.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (email_address : string) : t = {
    email_address = email_address;
    company_name = None;
    send_opt_in_options = None;
}

