(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    verified: bool option [@default None];
    email_address: string;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (email_address : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    verified = None;
    email_address = email_address;
    created_at = created_at;
    updated_at = updated_at;
}

