(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* ID of the inbox. The ID is a UUID-V4 format string. Use the inboxId for calls to Inbox and Email Controller endpoints. See the emailAddress property for the email address or the inbox. To get emails in an inbox use the WaitFor and Inbox Controller methods `waitForLatestEmail` and `getEmails` methods respectively. Inboxes can be used with aliases to forward emails automatically. *)
    id: string option [@default None];
    (* When the inbox was created. Time stamps are in ISO DateTime Format `yyyy-MM-dd'T'HH:mm:ss.SSSXXX` e.g. `2000-10-31T01:30:00.000-05:00`. *)
    created_at: string option [@default None];
    (* Name of the inbox and used as the sender name when sending emails .Displayed in the dashboard for easier search *)
    name: string option [@default None];
    (* The inbox's email address. Inbox projections and previews may not include the email address. To view the email address fetch the inbox entity directly. Send an email to this address and the inbox will receive and store it for you. Note the email address in MailSlurp match characters exactly and are case sensitive so `+123` additions are considered different addresses. To retrieve the email use the Inbox and Email Controller endpoints with the inbox ID. *)
    email_address: string option [@default None];
    (* Is the inbox a favorite inbox. Make an inbox a favorite is typically done in the dashboard for quick access or filtering *)
    favourite: bool option [@default None];
    (* Tags that inbox has been tagged with. Tags can be added to inboxes to group different inboxes within an account. You can also search for inboxes by tag in the dashboard UI. *)
    tags: string list;
    (* Does inbox permit team access for organization team members. If so team users can use inbox and emails associated with it. See the team access guide at https://www.mailslurp.com/guides/team-email-account-sharing/ *)
    team_access: bool option [@default None];
    (* Type of inbox. HTTP inboxes are faster and better for most cases. SMTP inboxes are more suited for public facing inbound messages (but cannot send). *)
    inbox_type: Enums.inboxtype option [@default None];
    (* Is the inbox readOnly for the caller. Read only means can not be deleted or modified. This flag is present when using team accounts and shared inboxes. *)
    read_only: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    created_at = None;
    name = None;
    email_address = None;
    favourite = None;
    tags = [];
    team_access = None;
    inbox_type = None;
    read_only = None;
}

