(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Page_opt_in_identity_projection.t : Paginated opt in identity projections reflecting users who have verified double-opt in consent to receive emails from your account.
 *)

type t = {
    content: Opt_in_identity_projection.t list;
    pageable: Pageable_object.t option [@default None];
    total_elements: int64;
    total_pages: int32;
    last: bool option [@default None];
    number_of_elements: int32 option [@default None];
    sort: Sort_object.t option [@default None];
    first: bool option [@default None];
    size: int32 option [@default None];
    number: int32 option [@default None];
    empty: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Paginated opt in identity projections reflecting users who have verified double-opt in consent to receive emails from your account. *)
let create (total_elements : int64) (total_pages : int32) : t = {
    content = [];
    pageable = None;
    total_elements = total_elements;
    total_pages = total_pages;
    last = None;
    number_of_elements = None;
    sort = None;
    first = None;
    size = None;
    number = None;
    empty = None;
}

