(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    page_number: int32;
    page_size: int32;
} [@@deriving yojson { strict = false }, show ];;

let create (page_number : int32) (page_size : int32) : t = {
    page_number = page_number;
    page_size = page_size;
}

