(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _type: string option [@default None];
    carrier_name: string option [@default None];
    mobile_country_code: string option [@default None];
    mobile_network_code: string option [@default None];
    error_code: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    _type = None;
    carrier_name = None;
    mobile_country_code = None;
    mobile_network_code = None;
    error_code = None;
}

