(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    user_id: string;
    phone_country: Enums.phonecountry;
    phone_variant: Enums.phonevariant option [@default None];
    status: Enums.phoneprovisioningjobdto_status;
    requested_count: int32;
    attempted_count: int32;
    succeeded_count: int32;
    failed_count: int32;
    unavailable_count: int32;
    created_at: string;
    updated_at: string;
    items: Phone_provisioning_job_item_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (phone_country : Enums.phonecountry) (status : Enums.phoneprovisioningjobdto_status) (requested_count : int32) (attempted_count : int32) (succeeded_count : int32) (failed_count : int32) (unavailable_count : int32) (created_at : string) (updated_at : string) (items : Phone_provisioning_job_item_dto.t list) : t = {
    id = id;
    user_id = user_id;
    phone_country = phone_country;
    phone_variant = None;
    status = status;
    requested_count = requested_count;
    attempted_count = attempted_count;
    succeeded_count = succeeded_count;
    failed_count = failed_count;
    unavailable_count = unavailable_count;
    created_at = created_at;
    updated_at = updated_at;
    items = items;
}

