(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    country_code: string option [@default None];
    country_prefix: string option [@default None];
    phone_number: string;
    is_valid: bool;
    validation_errors: string list;
} [@@deriving yojson { strict = false }, show ];;

let create (phone_number : string) (is_valid : bool) : t = {
    country_code = None;
    country_prefix = None;
    phone_number = phone_number;
    is_valid = is_valid;
    validation_errors = [];
}

