(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    phone_number: string;
    national_format: string option [@default None];
    country_code: string option [@default None];
    country_prefix: string option [@default None];
    is_valid: bool;
    validation_errors: string list;
    line_type_intelligence: Phone_number_line_type_intelligence_dto.t option [@default None];
    mailslurp_phone_number: bool;
} [@@deriving yojson { strict = false }, show ];;

let create (phone_number : string) (is_valid : bool) (mailslurp_phone_number : bool) : t = {
    phone_number = phone_number;
    national_format = None;
    country_code = None;
    country_prefix = None;
    is_valid = is_valid;
    validation_errors = [];
    line_type_intelligence = None;
    mailslurp_phone_number = mailslurp_phone_number;
}

