(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Phone_number_projection.t : Phone number projection
 *)

type t = {
    user_id: string;
    created_at: string;
    phone_country: Enums.phonecountry;
    phone_number: string;
    name: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Phone number projection *)
let create (user_id : string) (created_at : string) (phone_country : Enums.phonecountry) (phone_number : string) (id : string) : t = {
    user_id = user_id;
    created_at = created_at;
    phone_country = phone_country;
    phone_number = phone_number;
    name = None;
    id = id;
}

