(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    last_body: string;
    phone_number: string;
    phone_number_id: string;
    other_phone_number: string;
    last_message_direction: Enums.lastmessagedirection;
    last_created: string;
} [@@deriving yojson { strict = false }, show ];;

let create (last_body : string) (phone_number : string) (phone_number_id : string) (other_phone_number : string) (last_message_direction : Enums.lastmessagedirection) (last_created : string) : t = {
    last_body = last_body;
    phone_number = phone_number;
    phone_number_id = phone_number_id;
    other_phone_number = other_phone_number;
    last_message_direction = last_message_direction;
    last_created = last_created;
}

