(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    phone_country_summaries: Phone_summary_country_dto.t list;
    has_phone_numbers: bool;
    has_missing_plans: bool;
    total_phones: int32;
    plans: Plan_summary_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (phone_country_summaries : Phone_summary_country_dto.t list) (has_phone_numbers : bool) (has_missing_plans : bool) (total_phones : int32) (plans : Plan_summary_dto.t list) : t = {
    phone_country_summaries = phone_country_summaries;
    has_phone_numbers = has_phone_numbers;
    has_missing_plans = has_missing_plans;
    total_phones = total_phones;
    plans = plans;
}

