(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    pool_id: string;
    phone_number_id: string;
    phone_number: string;
    phone_country: Enums.phonecountry;
    phone_name: string option [@default None];
    lease_name: string option [@default None];
    lease_owner: string option [@default None];
    leased_at: string;
    expires_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (pool_id : string) (phone_number_id : string) (phone_number : string) (phone_country : Enums.phonecountry) (leased_at : string) : t = {
    id = id;
    pool_id = pool_id;
    phone_number_id = phone_number_id;
    phone_number = phone_number;
    phone_country = phone_country;
    phone_name = None;
    lease_name = None;
    lease_owner = None;
    leased_at = leased_at;
    expires_at = None;
}

