(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    user_id: string;
    compliance_address: string option [@default None];
    emergency_address: string option [@default None];
    phone_number: string;
    phone_country: Enums.isocountrycode;
    phone_plan: string;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (phone_number : string) (phone_country : Enums.isocountrycode) (phone_plan : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    user_id = user_id;
    compliance_address = None;
    emergency_address = None;
    phone_number = phone_number;
    phone_country = phone_country;
    phone_plan = phone_plan;
    created_at = created_at;
    updated_at = updated_at;
}

