(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    items: Phone_plan_availability_item.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (items : Phone_plan_availability_item.t list) : t = {
    items = items;
}

