(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    phone_number: string;
    provider_label: string option [@default None];
    status: Enums.phoneprovisioningjobitemdto_status;
    line_type: string option [@default None];
    carrier_name: string option [@default None];
    mobile_country_code: string option [@default None];
    mobile_network_code: string option [@default None];
    phone_number_id: string option [@default None];
    failure_message: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (phone_number : string) (status : Enums.phoneprovisioningjobitemdto_status) : t = {
    id = id;
    phone_number = phone_number;
    provider_label = None;
    status = status;
    line_type = None;
    carrier_name = None;
    mobile_country_code = None;
    mobile_network_code = None;
    phone_number_id = None;
    failure_message = None;
}

