(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    updated_at: string;
    user_id: string;
    inbox_id: string;
    created_at: string;
    plus_address: string;
    full_address: string;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

let create (updated_at : string) (user_id : string) (inbox_id : string) (created_at : string) (plus_address : string) (full_address : string) (id : string) : t = {
    updated_at = updated_at;
    user_id = user_id;
    inbox_id = inbox_id;
    created_at = created_at;
    plus_address = plus_address;
    full_address = full_address;
    id = id;
}

