(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    mail_provider: Enums.mailprovider;
    imap_host: string;
    imap_port: int32;
    imap_ssl: bool;
    imap_start_tls: bool option [@default None];
    smtp_host: string;
    smtp_port: int32;
    smtp_ssl: bool;
    smtp_start_tls: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (mail_provider : Enums.mailprovider) (imap_host : string) (imap_port : int32) (imap_ssl : bool) (smtp_host : string) (smtp_port : int32) (smtp_ssl : bool) : t = {
    mail_provider = mail_provider;
    imap_host = imap_host;
    imap_port = imap_port;
    imap_ssl = imap_ssl;
    imap_start_tls = None;
    smtp_host = smtp_host;
    smtp_port = smtp_port;
    smtp_ssl = smtp_ssl;
    smtp_start_tls = None;
}

