(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Raw_email_json.t : Content in raw format
 *)

type t = {
    content: string;
} [@@deriving yojson { strict = false }, show ];;

(** Content in raw format *)
let create (content : string) : t = {
    content = content;
}

