(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    raw_value: string option [@default None];
    email_address: string option [@default None];
    name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    raw_value = None;
    email_address = None;
    name = None;
}

