(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    email_address: string;
    raw_value: string;
} [@@deriving yojson { strict = false }, show ];;

let create (email_address : string) (raw_value : string) : t = {
    name = None;
    email_address = email_address;
    raw_value = raw_value;
}

