(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Reply_to_alias_email_options.t : Options for replying to an alias email using the alias inbox
 *)

type t = {
    (* List of uploaded attachments to send with the reply. Optional. *)
    attachments: string list;
    (* Body of the reply email you want to send *)
    body: string option [@default None];
    (* The charset that your message should be sent with. Optional. Default is UTF-8 *)
    charset: string option [@default None];
    (* Is the reply HTML *)
    is_html: bool option [@default None];
    (* When to send the email. Typically immediately *)
    send_strategy: Enums.sendstrategy option [@default Some(`SINGLE_MESSAGE)];
    (* Template ID to use instead of body. Will use template variable map to fill defined variable slots. *)
    template: string option [@default None];
    (* Template variables if using a template *)
    template_variables: Yojson.Safe.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for replying to an alias email using the alias inbox *)
let create () : t = {
    attachments = [];
    body = None;
    charset = None;
    is_html = None;
    send_strategy = None;
    template = None;
    template_variables = None;
}

