(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    user_id: string;
    phone_number: string;
    from_number: string;
    to_number: string;
    body: string;
    sid: string;
    reply_to_sid: string option [@default None];
    reply_to_id: string option [@default None];
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (user_id : string) (phone_number : string) (from_number : string) (to_number : string) (body : string) (sid : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    user_id = user_id;
    phone_number = phone_number;
    from_number = from_number;
    to_number = to_number;
    body = body;
    sid = sid;
    reply_to_sid = None;
    reply_to_id = None;
    created_at = created_at;
    updated_at = updated_at;
}

