(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    from: string option [@default None];
    sender: Sender.t option [@default None];
    recipients: Email_recipients.t option [@default None];
    subject: string option [@default None];
    inbox_id: string;
    user_id: string;
    attachments: string list;
    created_at: string;
    _to: string list;
    cc: string list;
    bcc: string list;
    message_id: string option [@default None];
    in_reply_to: string option [@default None];
    body_excerpt: string option [@default None];
    text_excerpt: string option [@default None];
    body_md5_hash: string option [@default None];
    virtual_send: bool;
    thread_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (inbox_id : string) (user_id : string) (created_at : string) (_to : string list) (cc : string list) (bcc : string list) (virtual_send : bool) : t = {
    id = id;
    from = None;
    sender = None;
    recipients = None;
    subject = None;
    inbox_id = inbox_id;
    user_id = user_id;
    attachments = [];
    created_at = created_at;
    _to = _to;
    cc = cc;
    bcc = bcc;
    message_id = None;
    in_reply_to = None;
    body_excerpt = None;
    text_excerpt = None;
    body_md5_hash = None;
    virtual_send = virtual_send;
    thread_id = None;
}

