(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sent_email_dto.t : Sent email details
 *)

type t = {
    (* ID of sent email *)
    id: string;
    (* User ID *)
    user_id: string;
    (* Inbox ID email was sent from *)
    inbox_id: string;
    (* Domain ID *)
    domain_id: string option [@default None];
    (* Recipients email was sent to *)
    _to: string list;
    from: string option [@default None];
    reply_to: string option [@default None];
    cc: string list;
    bcc: string list;
    (* Array of IDs of attachments that were sent with this email *)
    attachments: string list;
    subject: string option [@default None];
    (* MD5 Hash *)
    body_md5_hash: string option [@default None];
    body: string option [@default None];
    to_contacts: string list;
    to_group: string option [@default None];
    charset: string option [@default None];
    is_html: bool option [@default None];
    sent_at: string;
    pixel_ids: string list;
    message_id: string option [@default None];
    message_ids: string list;
    virtual_send: bool option [@default None];
    template_id: string option [@default None];
    template_variables: (string * Yojson.Safe.t) list;
    html: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Sent email details *)
let create (id : string) (user_id : string) (inbox_id : string) (sent_at : string) : t = {
    id = id;
    user_id = user_id;
    inbox_id = inbox_id;
    domain_id = None;
    _to = [];
    from = None;
    reply_to = None;
    cc = [];
    bcc = [];
    attachments = [];
    subject = None;
    body_md5_hash = None;
    body = None;
    to_contacts = [];
    to_group = None;
    charset = None;
    is_html = None;
    sent_at = sent_at;
    pixel_ids = [];
    message_id = None;
    message_ids = [];
    virtual_send = None;
    template_id = None;
    template_variables = [];
    html = None;
}

