(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sent_email_projection.t : Collection of items
 *)

type t = {
    id: string;
    from: string option [@default None];
    user_id: string;
    subject: string option [@default None];
    created_at: string;
    inbox_id: string;
    _to: string list;
    attachments: string list;
    bcc: string list;
    cc: string list;
    body_md5_hash: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Collection of items *)
let create (id : string) (user_id : string) (created_at : string) (inbox_id : string) (_to : string list) (attachments : string list) (bcc : string list) (cc : string list) : t = {
    id = id;
    from = None;
    user_id = user_id;
    subject = None;
    created_at = created_at;
    inbox_id = inbox_id;
    _to = _to;
    attachments = attachments;
    bcc = bcc;
    cc = cc;
    body_md5_hash = None;
}

