(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sent_email_dto.t : Sent email details
 *)

type t = {
    (* ID of sent email *)
    id: string;
    (* User ID *)
    user_id: string;
    (* Inbox ID email was sent from *)
    inbox_id: string;
    (* Domain ID *)
    domain_id: string option [@default None];
    (* Recipients email was sent to *)
    _to: string list;
    (* Sent from address *)
    from: string option [@default None];
    sender: Sender.t option [@default None];
    recipients: Email_recipients.t option [@default None];
    reply_to: string option [@default None];
    cc: string list;
    bcc: string list;
    (* Array of IDs of attachments that were sent with this email *)
    attachments: string list;
    subject: string option [@default None];
    (* MD5 Hash *)
    body_md5_hash: string option [@default None];
    (* Sent email body *)
    body: string option [@default None];
    to_contacts: string list;
    to_group: string option [@default None];
    charset: string option [@default None];
    is_html: bool option [@default None];
    sent_at: string;
    created_at: string;
    pixel_ids: string list;
    (* RFC 5322 Message-ID header value without angle brackets. *)
    message_id: string option [@default None];
    message_ids: string list;
    virtual_send: bool option [@default None];
    template_id: string option [@default None];
    template_variables: (string * Yojson.Safe.t) list;
    headers: (string * string) list;
    (* MailSlurp thread ID for email chain that enables lookup for In-Reply-To and References fields. *)
    thread_id: string option [@default None];
    (* An excerpt of the body of the email message for quick preview. Takes HTML content part if exists falls back to TEXT content part if not *)
    body_excerpt: string option [@default None];
    (* An excerpt of the body of the email message for quick preview. Takes TEXT content part if exists *)
    text_excerpt: string option [@default None];
    (* Parsed value of In-Reply-To header. A Message-ID in a thread. *)
    in_reply_to: string option [@default None];
    (* Is email favourited *)
    favourite: bool option [@default None];
    html: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Sent email details *)
let create (id : string) (user_id : string) (inbox_id : string) (sent_at : string) (created_at : string) : t = {
    id = id;
    user_id = user_id;
    inbox_id = inbox_id;
    domain_id = None;
    _to = [];
    from = None;
    sender = None;
    recipients = None;
    reply_to = None;
    cc = [];
    bcc = [];
    attachments = [];
    subject = None;
    body_md5_hash = None;
    body = None;
    to_contacts = [];
    to_group = None;
    charset = None;
    is_html = None;
    sent_at = sent_at;
    created_at = created_at;
    pixel_ids = [];
    message_id = None;
    message_ids = [];
    virtual_send = None;
    template_id = None;
    template_variables = [];
    headers = [];
    thread_id = None;
    body_excerpt = None;
    text_excerpt = None;
    in_reply_to = None;
    favourite = None;
    html = None;
}

