(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sent_sms_projection.t : Sent SMS projection
 *)

type t = {
    body: string;
    created_at: string;
    user_id: string;
    phone_number: string;
    from_number: string;
    to_number: string;
    reply_to_id: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Sent SMS projection *)
let create (body : string) (created_at : string) (user_id : string) (phone_number : string) (from_number : string) (to_number : string) (id : string) : t = {
    body = body;
    created_at = created_at;
    user_id = user_id;
    phone_number = phone_number;
    from_number = from_number;
    to_number = to_number;
    reply_to_id = None;
    id = id;
}

