(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Set_inbox_favourited_options.t : Options for setting inbox favourite state
 *)

type t = {
    (* Is the inbox a favorite. Marking an inbox as a favorite is typically done in the dashboard for quick access or filtering *)
    state: bool;
} [@@deriving yojson { strict = false }, show ];;

(** Options for setting inbox favourite state *)
let create (state : bool) : t = {
    state = state;
}

