(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* ID of inbox to send from. If null an inbox will be created for sending *)
    sender_id: string option [@default None];
    (* Email address to send to *)
    _to: string option [@default None];
    (* Body of the email message. Supports HTML *)
    body: string option [@default None];
    (* Subject line of the email *)
    subject: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    sender_id = None;
    _to = None;
    body = None;
    subject = None;
}

