(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sms_projection.t : SMS projection
 *)

type t = {
    body: string;
    created_at: string;
    user_id: string;
    phone_number: string;
    from_number: string;
    read: bool;
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** SMS projection *)
let create (body : string) (created_at : string) (user_id : string) (phone_number : string) (from_number : string) (read : bool) (id : string) : t = {
    body = body;
    created_at = created_at;
    user_id = user_id;
    phone_number = phone_number;
    from_number = from_number;
    read = read;
    id = id;
}

