(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Smtp_diagnostic_step.t : Structured SMTP diagnostic transcript entry
 *)

type t = {
    step: string;
    code: string option [@default None];
    message: string;
} [@@deriving yojson { strict = false }, show ];;

(** Structured SMTP diagnostic transcript entry *)
let create (step : string) (message : string) : t = {
    step = step;
    code = None;
    message = message;
}

