(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Structured_output_schema.t : JSON output schema for structured content repsonses. This schema dictates the format that an AI should use when responding to your instructions.
 *)

type t = {
    any_of: Structured_output_schema.t list;
    default: Yojson.Safe.t option [@default None];
    (* Provide a description of the schema to help the AI understand the schema. *)
    description: string option [@default None];
    (* When using type string and format enum pass a collection of enum values here. *)
    enum: string list;
    example: Yojson.Safe.t option [@default None];
    (* Format for string types. Can be null, date-time or enum. *)
    format: string option [@default None];
    items: Structured_output_schema.t option [@default None];
    max_items: int64 option [@default None];
    min_items: int64 option [@default None];
    max_length: int64 option [@default None];
    min_length: int64 option [@default None];
    pattern: string option [@default None];
    (* Properties of an OBJECT schema. These are key value pairs where the key is the property name and the value is the schema for that property. *)
    properties: (string * Structured_output_schema.t) list;
    (* Pass an array of property names to specify the order of properties in the generated JSON object if required. *)
    property_ordering: string list;
    required: string list;
    max_properties: int64 option [@default None];
    min_properties: int64 option [@default None];
    maximum: float option [@default None];
    minimum: float option [@default None];
    nullable: bool option [@default None];
    title: string option [@default None];
    (* Primitive JSON schema types with a fallback CUSTOM for unknown values. *)
    _type: Enums.structuredoutputschema_type option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** JSON output schema for structured content repsonses. This schema dictates the format that an AI should use when responding to your instructions. *)
let create () : t = {
    any_of = [];
    default = None;
    description = None;
    enum = [];
    example = None;
    format = None;
    items = None;
    max_items = None;
    min_items = None;
    max_length = None;
    min_length = None;
    pattern = None;
    properties = [];
    property_ordering = [];
    required = [];
    max_properties = None;
    min_properties = None;
    maximum = None;
    minimum = None;
    nullable = None;
    title = None;
    _type = None;
}

