(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    content: string;
    created_at: string;
    id: string;
    name: string;
    variables: Template_variable.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (content : string) (created_at : string) (id : string) (name : string) (variables : Template_variable.t list) : t = {
    content = content;
    created_at = created_at;
    id = id;
    name = name;
    variables = variables;
}

