(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Template_projection.t : Email template data
 *)

type t = {
    name: string;
    id: string;
    variables: string list;
    created_at: string;
    updated_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** Email template data *)
let create (name : string) (id : string) (variables : string list) (created_at : string) (updated_at : string) : t = {
    name = name;
    id = id;
    variables = variables;
    created_at = created_at;
    updated_at = updated_at;
}

