(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    generated_at: string;
    user_id: string;
    findings: Tenant_reputation_finding_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (generated_at : string) (user_id : string) (findings : Tenant_reputation_finding_dto.t list) : t = {
    generated_at = generated_at;
    user_id = user_id;
    findings = findings;
}

