(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    account_region: Enums.accountregion;
    tenant_name: string;
    tenant_arn: string option [@default None];
    _type: string option [@default None];
    impact: string option [@default None];
    status: string option [@default None];
    description: string option [@default None];
    created_timestamp: string option [@default None];
    last_updated_timestamp: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (account_region : Enums.accountregion) (tenant_name : string) : t = {
    account_region = account_region;
    tenant_name = tenant_name;
    tenant_arn = None;
    _type = None;
    impact = None;
    status = None;
    description = None;
    created_timestamp = None;
    last_updated_timestamp = None;
}

