(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Test_inbox_ruleset_sending_options.t : Test options for inbox ruleset sending test
 *)

type t = {
    inbox_id: string;
    recipient: string;
} [@@deriving yojson { strict = false }, show ];;

(** Test options for inbox ruleset sending test *)
let create (inbox_id : string) (recipient : string) : t = {
    inbox_id = inbox_id;
    recipient = recipient;
}

