(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    inbox_forwarder_test_options: Inbox_forwarder_test_options.t option [@default None];
    create_inbox_forwarder_options: Create_inbox_forwarder_options.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    inbox_forwarder_test_options = None;
    create_inbox_forwarder_options = None;
}

