(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Test_ruleset_receiving_options.t : Test options for inbox ruleset receiving test or phone number receiving test
 *)

type t = {
    inbox_id: string option [@default None];
    phone_id: string option [@default None];
    from_sender: string;
} [@@deriving yojson { strict = false }, show ];;

(** Test options for inbox ruleset receiving test or phone number receiving test *)
let create (from_sender : string) : t = {
    inbox_id = None;
    phone_id = None;
    from_sender = from_sender;
}

