(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    html: string;
    id: string;
    recipient: string option [@default None];
    seen: bool;
    url: string;
} [@@deriving yojson { strict = false }, show ];;

let create (html : string) (id : string) (seen : bool) (url : string) : t = {
    html = html;
    id = id;
    recipient = None;
    seen = seen;
    url = url;
}

