(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Tracking_pixel_projection.t : Tracking pixel data
 *)

type t = {
    inbox_id: string option [@default None];
    user_id: string;
    sent_email_id: string option [@default None];
    created_at: string;
    recipient: string option [@default None];
    seen: bool;
    seen_at: string option [@default None];
    name: string option [@default None];
    id: string;
} [@@deriving yojson { strict = false }, show ];;

(** Tracking pixel data *)
let create (user_id : string) (created_at : string) (seen : bool) (id : string) : t = {
    inbox_id = None;
    user_id = user_id;
    sent_email_id = None;
    created_at = created_at;
    recipient = None;
    seen = seen;
    seen_at = None;
    name = None;
    id = id;
}

