(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Unknown_missed_email_projection.t : Unknown missed email projection
 *)

type t = {
    _to: string list;
    created_at: string;
    subject: string option [@default None];
    id: string;
    from: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Unknown missed email projection *)
let create (created_at : string) (id : string) : t = {
    _to = [];
    created_at = created_at;
    subject = None;
    id = id;
    from = None;
}

