(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Update_domain_monitor_options.t : Update options for a domain monitor
 *)

type t = {
    (* Optional display name *)
    name: string option [@default None];
    (* Interval in seconds *)
    interval_seconds: int64 option [@default None];
    (* Enable/disable scheduled monitor runs (legacy alias for schedulingEnabled) *)
    enabled: bool option [@default None];
    (* Enable/disable scheduled monitor runs. Direct run-now remains available. *)
    scheduling_enabled: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Update options for a domain monitor *)
let create () : t = {
    name = None;
    interval_seconds = None;
    enabled = None;
    scheduling_enabled = None;
}

