(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Update_inbox_replier_options.t : Options for updating an inbox replier
 *)

type t = {
    (* Inbox ID to attach replier to *)
    inbox_id: string;
    (* Name for replier *)
    name: string option [@default None];
    (* Field to match against to trigger inbox replier for inbound email *)
    field: Enums.inboxautomationmatchoption_field option [@default None];
    (* String or wildcard style match for field specified when evaluating reply rules *)
    _match: string option [@default None];
    (* Reply-to email address when sending replying *)
    reply_to: string option [@default None];
    (* Subject override when replying to email *)
    subject: string option [@default None];
    (* Send email from address *)
    from: string option [@default None];
    (* Email reply charset *)
    charset: string option [@default None];
    (* Send HTML email *)
    is_html: bool option [@default None];
    (* Ignore sender replyTo when responding. Send directly to the sender if enabled. *)
    ignore_reply_to: bool option [@default None];
    (* Email body for reply *)
    body: string option [@default None];
    (* ID of template to use when sending a reply *)
    template_id: string option [@default None];
    (* Template variable values *)
    template_variables: (string * Yojson.Safe.t) list;
    (* Comparison mode for inbox automation matching. *)
    should: Enums.inboxautomationmatchoption_should option [@default None];
    match_options: Inbox_automation_match_options.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for updating an inbox replier *)
let create (inbox_id : string) : t = {
    inbox_id = inbox_id;
    name = None;
    field = None;
    _match = None;
    reply_to = None;
    subject = None;
    from = None;
    charset = None;
    is_html = None;
    ignore_reply_to = None;
    body = None;
    template_id = None;
    template_variables = [];
    should = None;
    match_options = None;
}

