(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    email_address: string;
    account_state: Enums.accountstate;
    subscription_type: Enums.subscriptiontype option [@default None];
    account_type: Enums.accounttype;
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (email_address : string) (account_state : Enums.accountstate) (account_type : Enums.accounttype) (created_at : string) : t = {
    id = id;
    email_address = email_address;
    account_state = account_state;
    subscription_type = None;
    account_type = account_type;
    created_at = created_at;
}

