(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Validation_dto.t : Response object for email validation operation
 *)

type t = {
    (* ID of the email validated *)
    email_id: string option [@default None];
    html: Html_validation_result.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Response object for email validation operation *)
let create () : t = {
    email_id = None;
    html = None;
}

