(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Validation_dto.t : Response object for email validation operation
 *)

type t = {
    (* ID of the email validated *)
    email_id: string;
    html: Html_validation_result.t;
} [@@deriving yojson { strict = false }, show ];;

(** Response object for email validation operation *)
let create (email_id : string) (html : Html_validation_result.t) : t = {
    email_id = email_id;
    html = html;
}

