(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Verify_email_address_options.t : Options for verifying that an email address exists at a remote mail server.
 *)

type t = {
    mail_server_domain: string option [@default None];
    email_address: string;
    sender_email_address: string option [@default None];
    port: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Options for verifying that an email address exists at a remote mail server. *)
let create (email_address : string) : t = {
    mail_server_domain = None;
    email_address = email_address;
    sender_email_address = None;
    port = None;
}

