(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Wait_for_conditions.t : Conditions that a `waitForXEmails` endpoint operates on. The methods wait until given conditions are met or a timeout is reached. If the conditions are met without needing to wait the results will be returned immediately. Can include `unreadOnly` to ignore already read emails that were returned in an API call or viewing in the dashboard. Can also include matches for emails containing `from`, `subject`, `hasAttachments` etc.
 *)

type t = {
    (* Number of results that should match conditions. Either exactly or at least this amount based on the `countType`. If count condition is not met and the timeout has not been reached the `waitFor` method will retry the operation. *)
    count: int32 option [@default None];
    (* How should the found count be compared to the expected count. *)
    count_type: Enums.counttype option [@default None];
    (* ID of inbox to search within and apply conditions to. Essentially filtering the emails found to give a count. *)
    inbox_id: string option [@default None];
    (* Conditions that should be matched for an email to qualify for results. Each condition will be applied in order to each email within an inbox to filter a result list of matching emails you are waiting for. *)
    matches: Match_option.t list;
    (* Direction to sort matching emails by created time *)
    sort_direction: Enums.sortdirection option [@default None];
    (* Max time in milliseconds to retry the `waitFor` operation until conditions are met. *)
    timeout: int64 option [@default None];
    (* Apply conditions only to **unread** emails. All emails begin with `read=false`. An email is marked `read=true` when an `EmailDto` representation of it has been returned to the user at least once. For example you have called `getEmail` or `waitForLatestEmail` etc., or you have viewed the email in the dashboard.  *)
    unread_only: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Conditions that a `waitForXEmails` endpoint operates on. The methods wait until given conditions are met or a timeout is reached. If the conditions are met without needing to wait the results will be returned immediately. Can include `unreadOnly` to ignore already read emails that were returned in an API call or viewing in the dashboard. Can also include matches for emails containing `from`, `subject`, `hasAttachments` etc. *)
let create () : t = {
    count = None;
    count_type = None;
    inbox_id = None;
    matches = [];
    sort_direction = None;
    timeout = None;
    unread_only = None;
}

