(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    phone_number_id: string;
    timeout: int64;
    unread_only: bool option [@default None];
    before: string option [@default None];
    since: string option [@default None];
    sort_direction: Enums.sortdirection option [@default None];
    delay: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (phone_number_id : string) (timeout : int64) : t = {
    phone_number_id = phone_number_id;
    timeout = timeout;
    unread_only = None;
    before = None;
    since = None;
    sort_direction = None;
    delay = None;
}

