(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_bounce_recipient_payload.t : BOUNCE_RECIPIENT webhook payload. Sent to your webhook url endpoint via HTTP POST when an email caused a bounce to occur for a recipient. Save the recipient to a ban list of your server and avoid email them again.
 *)

type t = {
    (* Idempotent message ID. Store this ID locally or in a database to prevent message duplication. *)
    message_id: string;
    (* ID of webhook entity being triggered *)
    webhook_id: string;
    (* Name of the event type webhook is being triggered for. *)
    event_name: Enums.eventname;
    (* Name of the webhook being triggered *)
    webhook_name: string option [@default None];
    (* Email address that caused a bounce. Make note of the address and try not to message it again to preserve your reputation. *)
    recipient: string;
} [@@deriving yojson { strict = false }, show ];;

(** BOUNCE_RECIPIENT webhook payload. Sent to your webhook url endpoint via HTTP POST when an email caused a bounce to occur for a recipient. Save the recipient to a ban list of your server and avoid email them again. *)
let create (message_id : string) (webhook_id : string) (event_name : Enums.eventname) (recipient : string) : t = {
    message_id = message_id;
    webhook_id = webhook_id;
    event_name = event_name;
    webhook_name = None;
    recipient = recipient;
}

