(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_test_request.t : Result of webhook test request
 *)

type t = {
    url: string;
    _method: Enums.webhookdto_method;
    headers: (string * string) list;
    payload: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Result of webhook test request *)
let create (url : string) (_method : Enums.webhookdto_method) (headers : (string * string) list) : t = {
    url = url;
    _method = _method;
    headers = headers;
    payload = None;
}

