(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_projection.t : Representation of a webhook
 *)

type t = {
    name: string option [@default None];
    id: string option [@default None];
    updated_at: string option [@default None];
    url: string option [@default None];
    inbox_id: string option [@default None];
    event_name: Enums.eventname option [@default None];
    created_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Representation of a webhook *)
let create () : t = {
    name = None;
    id = None;
    updated_at = None;
    url = None;
    inbox_id = None;
    event_name = None;
    created_at = None;
}

