(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    url: string;
    health: Enums.healthstatus;
} [@@deriving yojson { strict = false }, show ];;

let create (url : string) (health : Enums.healthstatus) : t = {
    url = url;
    health = health;
}

