(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_new_attachment_payload.t : NEW_ATTACHMENT webhook payload
 *)

type t = {
    (* ID of attachment. Use the `AttachmentController` to *)
    attachment_id: string option [@default None];
    (* Size of attachment in bytes *)
    content_length: int64 option [@default None];
    (* Content type of attachment such as 'image/png' or 'application/pdf *)
    content_type: string option [@default None];
    (* Name of the event type webhook is being triggered for. *)
    event_name: Enums.eventname option [@default None];
    (* Idempotent message ID. Store this ID locally or in a database to prevent message duplication. *)
    message_id: string option [@default None];
    (* Filename of the attachment if present *)
    name: string option [@default None];
    (* ID of webhook entity being triggered *)
    webhook_id: string option [@default None];
    (* Name of the webhook being triggered *)
    webhook_name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** NEW_ATTACHMENT webhook payload *)
let create () : t = {
    attachment_id = None;
    content_length = None;
    content_type = None;
    event_name = None;
    message_id = None;
    name = None;
    webhook_id = None;
    webhook_name = None;
}

