(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_projection.t : Representation of a webhook
 *)

type t = {
    inbox_id: string option [@default None];
    event_name: Enums.eventname option [@default None];
    created_at: string;
    updated_at: string;
    phone_number_id: string option [@default None];
    name: string option [@default None];
    id: string;
    url: string;
} [@@deriving yojson { strict = false }, show ];;

(** Representation of a webhook *)
let create (created_at : string) (updated_at : string) (id : string) (url : string) : t = {
    inbox_id = None;
    event_name = None;
    created_at = created_at;
    updated_at = updated_at;
    phone_number_id = None;
    name = None;
    id = id;
    url = url;
}

