(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_test_response.t : Response from webhook test request
 *)

type t = {
    status_code: int32 option [@default None];
    message: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Response from webhook test request *)
let create () : t = {
    status_code = None;
    message = None;
}

