(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Webhook_new_contact_payload.t : NEW_CONTACT webhook payload. Sent to your webhook url endpoint via HTTP POST when an email is received by the inbox that your webhook is attached to that contains a recipient that has not been saved as a contact.
 *)

type t = {
    (* Idempotent message ID. Store this ID locally or in a database to prevent message duplication. *)
    message_id: string;
    (* ID of webhook entity being triggered *)
    webhook_id: string;
    (* Name of the webhook being triggered *)
    webhook_name: string option [@default None];
    (* Name of the event type webhook is being triggered for. *)
    event_name: Enums.eventname;
    (* Contact ID *)
    contact_id: string;
    (* Contact group ID *)
    group_id: string option [@default None];
    (* Contact first name *)
    first_name: string option [@default None];
    (* Contact last name *)
    last_name: string option [@default None];
    (* Contact company name *)
    company: string option [@default None];
    (* Primary email address for contact *)
    primary_email_address: string option [@default None];
    (* Email addresses for contact *)
    email_addresses: string list;
    (* Tags for contact *)
    tags: string list;
    meta_data: Yojson.Safe.t option [@default None];
    (* Has contact opted out of emails *)
    opt_out: bool;
    (* Date time of event creation *)
    created_at: string;
} [@@deriving yojson { strict = false }, show ];;

(** NEW_CONTACT webhook payload. Sent to your webhook url endpoint via HTTP POST when an email is received by the inbox that your webhook is attached to that contains a recipient that has not been saved as a contact. *)
let create (message_id : string) (webhook_id : string) (event_name : Enums.eventname) (contact_id : string) (email_addresses : string list) (tags : string list) (opt_out : bool) (created_at : string) : t = {
    message_id = message_id;
    webhook_id = webhook_id;
    webhook_name = None;
    event_name = event_name;
    contact_id = contact_id;
    group_id = None;
    first_name = None;
    last_name = None;
    company = None;
    primary_email_address = None;
    email_addresses = email_addresses;
    tags = tags;
    meta_data = None;
    opt_out = opt_out;
    created_at = created_at;
}

